import 'package:equatable/equatable.dart';

class PatientEntity extends Equatable {
  final int id;
  final String name;
  final String? phone;
  final String? email;
  final String? avatar;
  final String? gender;
  final String? dateOfBirth;
  final String? bloodType;
  final String? address;
  final String? emergencyContact;
  final String? emergencyPhone;
  final String? medicalNotes;
  final bool isActive;
  final String? lastVisit;
  final int? age;

  const PatientEntity({
    required this.id,
    required this.name,
    this.phone,
    this.email,
    this.avatar,
    this.gender,
    this.dateOfBirth,
    this.bloodType,
    this.address,
    this.emergencyContact,
    this.emergencyPhone,
    this.medicalNotes,
    this.isActive = true,
    this.lastVisit,
    this.age,
  });

  PatientEntity copyWith({
    int? id,
    String? name,
    String? phone,
    String? email,
    String? avatar,
    String? gender,
    String? dateOfBirth,
    String? bloodType,
    String? address,
    String? emergencyContact,
    String? emergencyPhone,
    String? medicalNotes,
    bool? isActive,
    String? lastVisit,
    int? age,
  }) {
    return PatientEntity(
      id: id ?? this.id,
      name: name ?? this.name,
      phone: phone ?? this.phone,
      email: email ?? this.email,
      avatar: avatar ?? this.avatar,
      gender: gender ?? this.gender,
      dateOfBirth: dateOfBirth ?? this.dateOfBirth,
      bloodType: bloodType ?? this.bloodType,
      address: address ?? this.address,
      emergencyContact: emergencyContact ?? this.emergencyContact,
      emergencyPhone: emergencyPhone ?? this.emergencyPhone,
      medicalNotes: medicalNotes ?? this.medicalNotes,
      isActive: isActive ?? this.isActive,
      lastVisit: lastVisit ?? this.lastVisit,
      age: age ?? this.age,
    );
  }

  String get initials =>
      name.split(' ').map((e) => e[0]).take(2).join('').toUpperCase();

  @override
  List<Object?> get props => [
        id, name, phone, email, avatar, gender, dateOfBirth, bloodType,
        address, emergencyContact, emergencyPhone, medicalNotes, isActive,
        lastVisit, age
      ];



    static   List<PatientEntity> dummyPatients = [
        PatientEntity(
          id: 1,
          name: 'Ahmed Ali',
          phone: '+20 123 456 7890',
          email: 'ahmed@example.com',
          gender: 'Male',
          age: 34,
          isActive: true,
          bloodType: 'A+',
          address: 'Cairo, Egypt',
          lastVisit: '2024-05-10',
        ),
        PatientEntity(
          id: 2,
          name: 'Sara Mohamed',
          phone: '+20 987 654 3210',
          email: 'sara@example.com',
          gender: 'Female',
          age: 28,
          isActive: true,
          bloodType: 'O-',
          address: 'Alexandria, Egypt',
          lastVisit: '2024-05-08',
        ),
        PatientEntity(
          id: 3,
          name: 'John Doe',
          phone: '+1 555 000 1111',
          email: 'john@example.com',
          gender: 'Male',
          age: 45,
          isActive: false,
          bloodType: 'B+',
          address: 'New York, USA',
          lastVisit: '2024-04-15',
        ),
        PatientEntity(
          id: 4,
          name: 'Emma Watson',
          phone: '+44 20 7946 0000',
          email: 'emma@example.com',
          gender: 'Female',
          age: 31,
          isActive: true,
          bloodType: 'AB+',
          address: 'London, UK',
          lastVisit: '2024-05-02',
        ),
         PatientEntity(
          id: 5,
          name: 'Ahmed Ali',
          phone: '+20 123 456 7890',
          email: 'ahmed@example.com',
          gender: 'Male',
          age: 34,
          isActive: true,
          bloodType: 'A+',
          address: 'Cairo, Egypt',
          lastVisit: '2024-05-10',
        ),
        PatientEntity(
          id: 6,
          name: 'Sara Mohamed',
          phone: '+20 987 654 3210',
          email: 'sara@example.com',
          gender: 'Female',
          age: 28,
          isActive: true,
          bloodType: 'O-',
          address: 'Alexandria, Egypt',
          lastVisit: '2024-05-08',
        ),
        PatientEntity(
          id: 7,
          name: 'John Doe',
          phone: '+1 555 000 1111',
          email: 'john@example.com',
          gender: 'Male',
          age: 45,
          isActive: false,
          bloodType: 'B+',
          address: 'New York, USA',
          lastVisit: '2024-04-15',
        ),
        PatientEntity(
          id: 8,
          name: 'Emma Watson',
          phone: '+44 20 7946 0000',
          email: 'emma@example.com',
          gender: 'Female',
          age: 31,
          isActive: true,
          bloodType: 'AB+',
          address: 'London, UK',
          lastVisit: '2024-05-02',
        ),
         PatientEntity(
          id: 9,
          name: 'Emma Watson',
          phone: '+44 20 7946 0000',
          email: 'emma@example.com',
          gender: 'Female',
          age: 31,
          isActive: true,
          bloodType: 'AB+',
          address: 'London, UK',
          lastVisit: '2024-05-02',
        ), PatientEntity(
          id: 10,
          name: 'Emma Watson',
          phone: '+44 20 7946 0000',
          email: 'emma@example.com',
          gender: 'Female',
          age: 31,
          isActive: true,
          bloodType: 'AB+',
          address: 'London, UK',
          lastVisit: '2024-05-02',
        ), PatientEntity(
          id: 11,
          name: 'Emma Watson',
          phone: '+44 20 7946 0000',
          email: 'emma@example.com',
          gender: 'Female',
          age: 31,
          isActive: true,
          bloodType: 'AB+',
          address: 'London, UK',
          lastVisit: '2024-05-02',
        ), PatientEntity(
          id: 12,
          name: 'Emma Watson',
          phone: '+44 20 7946 0000',
          email: 'emma@example.com',
          gender: 'Female',
          age: 31,
          isActive: true,
          bloodType: 'AB+',
          address: 'London, UK',
          lastVisit: '2024-05-02',
        ), PatientEntity(
          id: 13,
          name: 'Emma Watson',
          phone: '+44 20 7946 0000',
          email: 'emma@example.com',
          gender: 'Female',
          age: 31,
          isActive: true,
          bloodType: 'AB+',
          address: 'London, UK',
          lastVisit: '2024-05-02',
        ), PatientEntity(
          id: 14,
          name: 'Emma Watson',
          phone: '+44 20 7946 0000',
          email: 'emma@example.com',
          gender: 'Female',
          age: 31,
          isActive: true,
          bloodType: 'AB+',
          address: 'London, UK',
          lastVisit: '2024-05-02',
        ), PatientEntity(
          id: 15,
          name: 'Emma Watson',
          phone: '+44 20 7946 0000',
          email: 'emma@example.com',
          gender: 'Female',
          age: 31,
          isActive: true,
          bloodType: 'AB+',
          address: 'London, UK',
          lastVisit: '2024-05-02',
        ), PatientEntity(
          id: 16,
          name: 'Emma Watson',
          phone: '+44 20 7946 0000',
          email: 'emma@example.com',
          gender: 'Female',
          age: 31,
          isActive: true,
          bloodType: 'AB+',
          address: 'London, UK',
          lastVisit: '2024-05-02',
        ), PatientEntity(
          id: 17,
          name: 'Emma Watson',
          phone: '+44 20 7946 0000',
          email: 'emma@example.com',
          gender: 'Female',
          age: 31,
          isActive: true,
          bloodType: 'AB+',
          address: 'London, UK',
          lastVisit: '2024-05-02',
        ), PatientEntity(
          id: 18,
          name: 'Emma Watson',
          phone: '+44 20 7946 0000',
          email: 'emma@example.com',
          gender: 'Female',
          age: 31,
          isActive: true,
          bloodType: 'AB+',
          address: 'London, UK',
          lastVisit: '2024-05-02',
        ), PatientEntity(
          id: 19,
          name: 'Emma Watson',
          phone: '+44 20 7946 0000',
          email: 'emma@example.com',
          gender: 'Female',
          age: 31,
          isActive: true,
          bloodType: 'AB+',
          address: 'London, UK',
          lastVisit: '2024-05-02',
        ), PatientEntity(
          id: 20,
          name: 'Emma Watson',
          phone: '+44 20 7946 0000',
          email: 'emma@example.com',
          gender: 'Female',
          age: 31,
          isActive: true,
          bloodType: 'AB+',
          address: 'London, UK',
          lastVisit: '2024-05-02',
        ), PatientEntity(
          id: 21,
          name: 'Emma Watson',
          phone: '+44 20 7946 0000',
          email: 'emma@example.com',
          gender: 'Female',
          age: 31,
          isActive: true,
          bloodType: 'AB+',
          address: 'London, UK',
          lastVisit: '2024-05-02',
        ),
      ];  
}
