const Map<String, String> arEG = {
  "about_app": "عن التطبيق",
  "from_camera": "من الكاميرا",
  "from_gallery": "من المعرض",
  "confirm": "تأكيد",
  "cancel": "إلغاء",
  "enter": "دخول",
  "back": "رجوع",
  "next": "التالي",
  "done": "تم",
  "save": "حفظ",
  "start": "بدء",
  "end": "انهاء",
  "skip": "تخطي",
  "delete": "حذف",
  "edit": "تعديل",
  "add": "إضافة",
  "clear": "مسح",
  "search_anything": "بحث عن أي شيء",
  "search": "بحث",
  "no_data_to_copy": "لا يوجد بيانات للنسخ",
  "show_all": "عرض الكل",
  "?": "؟",
  "illustration_no_connection": "تم قطع الإتصال",
  "illustration_no_connection_details":
      "عذرا تم قطع الاتصال بالإنترنت , تأكد من الاتصال و أعد المحاولة في وقت لاحق",
  "illustration_something_went_wrong": "حدث خطأ ما",
  "illustration_something_went_wrong_details":
      "حدث خطأ ما , تأكد من اتصالك و أعد المحاولة في وقت لاحق",
  "illustration_no_notifications": "لا يوجد إشعارات",
  "illustration_no_notifications_details": "لا يوجد إشعارات حتى الآن",
  "illustration_unknown": "خطأ غير معروف",
  "illustration_unknown_details":
      "حدث خطأ غير معروف , يرجى المحاولة مرة أخرى في وقت لاحق",
  "validate_address": "عفوا لم يتم ادخال عنوان",
  "number_not_empty": "يجب ألا يكون الرقم فارغًا",
  "number_not_correct": "الرجاء إدخال رقم صالح",
  "number_not_minus": "لا يمكن أن يكون الرقم أقل من 1",
  "validate_admin_adjective": "عفوا لم يتم صفه المسؤول",
  "validate_age": "من فضلك أدخل عمر صحيح",
  "validate_age_limit": "يجب أن لا يقل العمر عن 16 سنة",
  "validate_city": "عفوا لم يتم اختيار مدينه",
  "validate_confirm_password": "عفوا كلمة المرور غير متطابقة",
  "validate_date_of_birth": "عفوا لم يتم ادخال تاريخ ميلاد",
  "validate_email": "عفوا لم يتم ادخال بريد مستخدم صحيح",
  "validate_email_2": "من فضلك أدخل بريد إلكتروني صحيح",
  "validate_empty_field":
      "الحقل فارغ. من فضلك تأكد من ملء بيانات الحقل المطلوبة",
  "field_required": "الحقل مطلوب",
  "validate_lang": "عفوا لم يتم اختيار اللغات",
  "validate_language": " يجب على الأقل أن تختار لغة واحدة للمتابعة",
  "validate_message": "عفوا لم يتم ادخال رسالة صحيحة",
  "validate_numeric": "يجب أن تكون البيانات المدخلة أرقام",
  "validate_offered_service": "عفوا لم يتم اختيار الخدمة المقدمة",
  "validate_password": "عفوا لم يتم ادخال كلمة مرور صحيحة",
  "validate_password_length": "يجب ألا تقل كلمة المرور عن 8 أحرف أو أرقام",
  "validate_phone": "عفوا لم يتم ادخال رقم هاتف صحيح",
  "validate_phone_is_real": "! حاول مرة أخرى برقم هاتف صحيح",
  "validate_promo": "عفوا لم يتم ادخال كود صحيح",
  "validate_skills": "عفوا لم يتم اختيار المهارات",
  "validate_username": "عفوا لم يتم ادخال اسم مستخدم صحيح",
  "validate_username_length": "يجب أن يكون اسم المستخدم مكون من أكثر من حرفين",
  "snack_check_ur_connection": "تأكد من اتصالك بالإنترنت",
  "snack_something_went_wrong": "حدث خطأ ما",
  "snack_success": "تم بنجاح",
  "snack_error": "حدث خطأ ما",
  "snack_login_success": "تم تسجيل الدخول بنجاح",
  "snack_logout_success": "تم تسجيل الخروج بنجاح",
  "snack_register_success": "تم التسجيل بنجاح",
  "snack_short_password": "كلمة المرور قصيرة جدا",
  "snack_validate_number": "يجب أن تكون البيانات المدخلة أرقام",
  "success_password": "تم تغيير كلمة المرور بنجاح",
  "success_phone_verify": "تم تفعيل الهاتف بنجاح",
  "success_message_sent": "تم إرسال الرسالة بنجاح",
  "success_username": "تم تغيير اسم المستخدم بنجاح",
  "success_birthday": "تم تغيير تاريخ الميلاد بنجاح",
  "success_image": "تم تغيير الصورة بنجاح",
  "retry": "اعادة المحاولة",

  /// TODO: add new keys
  "ex_bad_request": "خطأ في الطلب",
  "ex_unauthorized": "غير مصرح لك بالوصول",
  "ex_forbidden": "ممنوع",
  "ex_not_found": "غير موجود",
  "ex_method_not_allowed": "الطريقة غير مسموح بها",
  "ex_not_acceptable": "غير مقبول",
  "accept": "قبول",
  "reject": "رفض",
  "accept_trip": "قبول الرحله",
  "reject_trip": "رفض الرحله",
  "ex_request_timeout": "انتهت مهلة الطلب",
  "ex_conflict": "حدث تعارض",
  "ex_internal_Server": "خطأ في الخادم",
  "ex_not_implemented": "لم يتم تنفيذه",
  "ex_bad_gateway": "بوابة سيئة",
  "ex_service_unavailable": "الخدمة غير متوفرة",
  "ex_gateway_timeout": "انتهت مهلة البوابة",
  "ex_unknown": "خطأ غير معروف",
  "ex_network": "خطأ في الشبكة",

  ///todo: add new keys of Anjo
  "login": "تسجيل الدخول",
  "dont_have_account": "ليس لديك حساب ؟",
  "enter_phone_number": "أدخل رقم الهاتف",
  "have_account": "لديك حساب بالفعل ؟",
  "create_account": "إنشاء حساب ",
  "logout": "تسجيل الخروج",
  "change_password": "تغيير كلمة المرور",
  "confirm_password": "تأكيد كلمة المرور",
  "phone_number": "رقم الموبايل",
  "phone": "الهاتف",
  "password": "كلمة المرور",
  "forget_password": "نسيت كلمة المرور ؟",
  "new_password": "كلمة المرور الجديدة",
  "reset_password_tip":
      "ادخل كلمة مرور قوية تحتوي على الاقل \nأحروف و ارقام و رموز",
  "enter_new_password": "أدخل كلمة المرور الجديدة",
  "user_name": "اسم المستخدم",
  "email": "البريد الإلكتروني",
  "register_now": "سجل الآن",
  "new_user": " جديد لدينا ؟",
  "delete_account": "حذف الحساب",
  "account_settings": "إعدادات الحساب",
  "support": "تواصل مع الدعم",
  "about": "عن التطبيق",
  "home": "الرئيسية",
  "privacy_policy": "سياسة الخصوصية",
  "terms_and_conditions": "الشروط و الأحكام",
  "see_more": "عرض الكل",
  "android": "أندرويد",
  "ios": "آيفون",
  "web": "ويب",
  "validate_phone_length": "يجب أن يكون رقم الهاتف مكون من 11 رقم",
  "skip_to": "تخطى",
  "onBoarding_title_1":
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص ",
  "onBoarding_body_1": "خدمة سيارات الإسعاف المجهزة طبيا",
  "onBoarding_title_2":
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص ",
  "onBoarding_body_2": "خدمة جدولة طلب سيارات الإسعاف",
  "onBoarding_title_3":
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص ",
  "onBoarding_body_3": "خدمة التنقل بين المدن",
  "onBoarding_body_4":
      "محتاج تشوف البهجه وتحس بالوان عصريه ووميزه مع دهانات انجو هتحس بكل تفاصيل البهجه اللي بتميز بيتك",
  "login_tips": "ادخل رقم الموبيل الخاص بك لتسجيل الدخول \nاو انشاء حساب جديد",
  "welcome_back": "مرحبا بك مرة اخري",
  "register_tip": "قم انشاء حسابك و استمتع بأفضل خدمات حجز الرحلات",
  "full_name": "الاسم بالكامل",
  "emial": "البريد الالكتروني",
  "complete_register": "اكمال التسجيل",
  "some_questions": " الاسئلة الشائعة ",
  "add_review": "اضافة تقييم ",
  "reset_password": "إسترجاع كلمة المرور",
  "code_verify": "التحقق من الكود",
  "check_phone_tip":
      "أدخل رقم جوال حسابك حتي نرسل إليك رمز\nيمكنك من خلاله تغير كلمة مرور",
  "check_phone_tip2": "يمكنك من خلاله تغير كلمة مرور",
  "send_code": "ارسال",
  "confirm_code": "تأكيد الكود التعريفي",
  "code_sent":
      "لقد قمنا بارسال رمز التأكيد مكون من\n6 رموز علي رقم الموبيل الخاص بك",
  "code_sent_two": "6 رموز على رقم الموبيل الخاص بك ",
  "resend_faild": "لم تستلم رساله بعد؟",
  "send_again": "اعادة الارسال بعد",
  "confirm_new_password": "تاكيد كلمة المرور الجديدة",
  "success_change_password": "تم تغيير كلمة السر بنجاح",
  "success_tip": "لقد تم تغير كلمة السر بنجاح قم بالذهاب ",
  "success_tip_2": "الي تسجيل الدخول مرة اخري",
  "back_to_login": "العودة لتسجيل الدخول",
  "complete_data_to_register": "أكمل البيانات لإنشاء حساب",

  "success_register": "تم انشاء حسابك بنجاح",
  "sucess_register_tip": "يمكنك الان الاستمتاع بخدمات انجو ",
  "sucess_register_tip_two": "بكل سهولة و يسر و الاستفاده بجميع نقاط الشراء",

  /// New Translate ///

  "enter_full_name": "ادخل الاسم الكامل",
  "enter_email": "ادخل البريد الالكتروني",
  "chosse_role": "اختر الدور",
  "enter_password": "ادخل كلمة المرور",
  "enter_confirm_password": "ادخل تأكيد كلمة المرور",

  /// ── Add Patient Step-by-Step ──
  "step": "خطوة",
  "submit": "إرسال",
  "return_to_main": "العودة للرئيسية",
  "filled": "مكتملة",
  "completed": "مكتمل",
  "patient_information": "معلومات المريض",
  "medical_status_history": "الحالة الطبية والتاريخ",
  "media_attachments": "المرفقات والوسائط",
  "administrative_details": "التفاصيل الإدارية",
  "add_new_patient": "إضافة مريض جديد",
  "fill_in_the_patient_details_below": "أدخل بيانات المريض بالأسفل",

  /// New App branch translate
  "caredesk_pro": "كير ديسك برو",
  "the_complete_ecosystem_for_modern_healthcare_management_experience_the_future_of_clinic_operations":
      "النظام البيئي المتكامل لإدارة الرعاية الصحية الحديثة. تجربة مستقبل إدارة العيادات.",
  "toggle_sidebar": "تبديل الشريط الجانبي",
  "search_patients_doctors...": "ابحث عن المرضى والأطباء ...",
  "Welcome_Back": "مرحبا بك",
  "Here's_what's_happening_at_your_clinic_today":
      "اكتشف أحدث الاتجاهات في الرعاية الصحية، وشارك قصص نجاح المرضى، وتعمّق في تحليلات البيانات المتقدمة لاتخاذ قرارات مستنيرة.",
  "export_report": "تصدير التقرير",
  "new_appointment": "حجز موعد جديد",
  "weekly_appointments_trend": "تحليل شامل للاتجاهات الأسبوعية",
  "Mon": "الاثنين",
  "Tue": "الثلاثاء",
  "Wed": "الاربعاء",
  "Thu": "الخميس",
  "Fri": "الجمعة",
  "Sat": "السبت",
  "Sun": "الاحد",
  "clinic_report_exported_successfully_as": "تم تصدير تقرير العيادة بنجاح باسم",
  "total_patients": "إجمالي عدد المرضى",
  "appointments_today": "مواعيد اليوم",
  "total_revenue": "إجمالي الإيرادات",
  "active_doctors": "عدد الأطباء",
  "appointments_in_progress": "المواعيد قيد التنفيذ",
  "total_new_patients": "عدد المرضى الجدد",
  "pending_appointments": "المواعيد المعلقة",
  "completed_appointments": "المواعيد المكتملة",
  "revenue_overview": "نظره عامة على الإيرادات",
  "demographics": "التركيبة السكانية",
  "quick_actions": "الإجراءات السريعة",
  "create_invoice": "إنشاء فاتورة",
  "manage_schedule": "إدارة الجدول",
  "recent_activity": "اخر الانشطة",
  "new_appointment_scheduled": "حجز موعد جديد",
  "appointment_reminder_sent": "تم إرسال تذكير بالموعد",
  "ago": "منذ",
  "select_your_preferred_document_format_to_download_the_comprehensive_clinic_performance_report":
      "اختر تنسيق المستند المفضل لديك لتنزيل تقرير أداء العيادة الشامل.",
  "perfect_for_printing_and_sharing_official_reports": "مثالي للطباعة ومشاركة التقارير الرسمية",
  "ideal_for_detailed_custom_data_analysis": "مثالي لتحليل البيانات المخصص المفصل",
  "lightweight_format_for_database_imports": "تنسيق خفيف للواردات قاعدة البيانات",
  "generating": "جاري التحضير",
  "Exporting": "جاري التصدير",
  "download_report": "تحميل التقرير",
  "report": "التقرير",
  "please_do_not_close_this_window": "الرجاء عدم إغلاق هذه النافذة",
};
