const Map<String, String> arEG = {
  "about_app": "عن التطبيق",
  "from_camera": "من الكاميرا",
  "from_gallery": "من المعرض",
  "confirm": "تأكيد",
  "cancel": "إلغاء",
  "enter": "دخول",
  "back": "رجوع",
  "next": "التالي",
  "done": "تم",
  "save": "حفظ",
  "start": "بدء",
  "end": "انهاء",
  "skip": "تخطي",
  "delete": "حذف",
  "edit": "تعديل",
  "add": "إضافة",
  "clear": "مسح",
  "search_anything": "بحث عن أي شيء",
  "search": "بحث",
  "no_data_to_copy": "لا يوجد بيانات للنسخ",
  "show_all": "عرض الكل",
  "?": "؟",
  "internet_connection_problem":
      "يوجد مشكلة في الاتصال بالإنترنت. يرجى المحاولة مرة أخرى.",
  "try_again": "أعد المحاولة",
  "connected": "متصل",
  "internet_restored": "تم استعادة الاتصال بالإنترنت.",
  "illustration_no_connection": "تم قطع الإتصال",
  "illustration_no_connection_details":
      "عذرا تم قطع الاتصال بالإنترنت , تأكد من الاتصال و أعد المحاولة في وقت لاحق",
  "illustration_something_went_wrong": "حدث خطأ ما",
  "illustration_something_went_wrong_details":
      "حدث خطأ ما , تأكد من اتصالك و أعد المحاولة في وقت لاحق",
  "illustration_no_notifications": "لا يوجد إشعارات",
  "illustration_no_notifications_details": "لا يوجد إشعارات حتى الآن",
  "illustration_unknown": "خطأ غير معروف",
  "illustration_unknown_details":
      "حدث خطأ غير معروف , يرجى المحاولة مرة أخرى في وقت لاحق",
  "validate_address": "عفوا لم يتم ادخال عنوان",
  "number_not_empty": "يجب ألا يكون الرقم فارغًا",
  "number_not_correct": "الرجاء إدخال رقم صالح",
  "number_not_minus": "لا يمكن أن يكون الرقم أقل من 1",
  "validate_admin_adjective": "عفوا لم يتم صفه المسؤول",
  "validate_age": "من فضلك أدخل عمر صحيح",
  "validate_age_limit": "يجب أن لا يقل العمر عن 16 سنة",
  "validate_city": "عفوا لم يتم اختيار مدينه",
  "validate_confirm_password": "عفوا كلمة المرور غير متطابقة",
  "validate_date_of_birth": "عفوا لم يتم ادخال تاريخ ميلاد",
  "validate_email": "عفوا لم يتم ادخال بريد مستخدم صحيح",
  "validate_email_2": "من فضلك أدخل بريد إلكتروني صحيح",
  "validate_empty_field":
      "الحقل فارغ. من فضلك تأكد من ملء بيانات الحقل المطلوبة",
  "field_required": "الحقل مطلوب",
  "validate_lang": "عفوا لم يتم اختيار اللغات",
  "validate_language": " يجب على الأقل أن تختار لغة واحدة للمتابعة",
  "validate_message": "عفوا لم يتم ادخال رسالة صحيحة",
  "validate_numeric": "يجب أن تكون البيانات المدخلة أرقام",
  "validate_offered_service": "عفوا لم يتم اختيار الخدمة المقدمة",
  "validate_password": "عفوا لم يتم ادخال كلمة مرور صحيحة",
  "validate_password_length": "يجب ألا تقل كلمة المرور عن 8 أحرف أو أرقام",
  "validate_phone": "عفوا لم يتم ادخال رقم هاتف صحيح",
  "validate_phone_is_real": "! حاول مرة أخرى برقم هاتف صحيح",
  "validate_promo": "عفوا لم يتم ادخال كود صحيح",
  "validate_skills": "عفوا لم يتم اختيار المهارات",
  "validate_username": "عفوا لم يتم ادخال اسم مستخدم صحيح",
  "validate_username_length": "يجب أن يكون اسم المستخدم مكون من أكثر من حرفين",
  "snack_check_ur_connection": "تأكد من اتصالك بالإنترنت",
  "snack_something_went_wrong": "حدث خطأ ما",
  "snack_success": "تم بنجاح",
  "snack_error": "حدث خطأ ما",
  "snack_login_success": "تم تسجيل الدخول بنجاح",
  "snack_logout_success": "تم تسجيل الخروج بنجاح",
  "snack_register_success": "تم التسجيل بنجاح",
  "snack_short_password": "كلمة المرور قصيرة جدا",
  "snack_validate_number": "يجب أن تكون البيانات المدخلة أرقام",
  "success_password": "تم تغيير كلمة المرور بنجاح",
  "success_phone_verify": "تم تفعيل الهاتف بنجاح",
  "success_message_sent": "تم إرسال الرسالة بنجاح",
  "success_username": "تم تغيير اسم المستخدم بنجاح",
  "success_birthday": "تم تغيير تاريخ الميلاد بنجاح",
  "success_image": "تم تغيير الصورة بنجاح",
  "retry": "اعادة المحاولة",

  /// TODO: add new keys
  "ex_bad_request": "خطأ في الطلب",
  "ex_unauthorized": "غير مصرح لك بالوصول",
  "ex_forbidden": "ممنوع",
  "ex_not_found": "غير موجود",
  "ex_method_not_allowed": "الطريقة غير مسموح بها",
  "ex_not_acceptable": "غير مقبول",
  "accept": "قبول",
  "reject": "رفض",
  "accept_trip": "قبول الرحله",
  "reject_trip": "رفض الرحله",
  "ex_request_timeout": "انتهت مهلة الطلب",
  "ex_conflict": "حدث تعارض",
  "ex_internal_Server": "خطأ في الخادم",
  "ex_not_implemented": "لم يتم تنفيذه",
  "ex_bad_gateway": "بوابة سيئة",
  "ex_service_unavailable": "الخدمة غير متوفرة",
  "ex_gateway_timeout": "انتهت مهلة البوابة",
  "ex_unknown": "خطأ غير معروف",
  "ex_network": "خطأ في الشبكة",

  ///todo: add new keys of Anjo
  "login": "تسجيل الدخول",
  "dont_have_account": "ليس لديك حساب ؟",
  "enter_phone_number": "أدخل رقم الهاتف",
  "have_account": "لديك حساب بالفعل ؟",
  "create_account": "إنشاء حساب ",
  "logout": "تسجيل الخروج",
  "change_password": "تغيير كلمة المرور",
  "confirm_password": "تأكيد كلمة المرور",
  "phone_number": "رقم الموبايل",
  "phone": "الهاتف",
  "password": "كلمة المرور",
  "forget_password": "نسيت كلمة المرور ؟",
  "new_password": "كلمة المرور الجديدة",
  "reset_password_tip":
      "ادخل كلمة مرور قوية تحتوي على الاقل \nأحروف و ارقام و رموز",
  "enter_new_password": "أدخل كلمة المرور الجديدة",
  "user_name": "اسم المستخدم",
  "email": "البريد الإلكتروني",
  "register_now": "سجل الآن",
  "new_user": " جديد لدينا ؟",
  "delete_account": "حذف الحساب",
  "account_settings": "إعدادات الحساب",
  "support": "تواصل مع الدعم",
  "about": "عن التطبيق",
  "home": "الرئيسية",
  "privacy_policy": "سياسة الخصوصية",
  "terms_and_conditions": "الشروط و الأحكام",
  "see_more": "عرض الكل",
  "android": "أندرويد",
  "ios": "آيفون",
  "web": "ويب",
  "validate_phone_length": "يجب أن يكون رقم الهاتف مكون من 11 رقم",
  "skip_to": "تخطى",
  "onBoarding_title_1":
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص ",
  "onBoarding_body_1": "خدمة سيارات الإسعاف المجهزة طبيا",
  "onBoarding_title_2":
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص ",
  "onBoarding_body_2": "خدمة جدولة طلب سيارات الإسعاف",
  "onBoarding_title_3":
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص ",
  "onBoarding_body_3": "خدمة التنقل بين المدن",
  "onBoarding_body_4":
      "محتاج تشوف البهجه وتحس بالوان عصريه ووميزه مع دهانات انجو هتحس بكل تفاصيل البهجه اللي بتميز بيتك",
  "login_tips": "ادخل رقم الموبيل الخاص بك لتسجيل الدخول \nاو انشاء حساب جديد",
  "register_tip": "قم انشاء حسابك و استمتع بأفضل خدمات حجز الرحلات",
  "full_name": "الاسم بالكامل",
  "emial": "البريد الالكتروني",
  "complete_register": "اكمال التسجيل",
  "some_questions": " الاسئلة الشائعة ",
  "add_review": "اضافة تقييم ",
  "reset_password": "إسترجاع كلمة المرور",
  "code_verify": "التحقق من الكود",
  "check_phone_tip":
      "أدخل رقم جوال حسابك حتي نرسل إليك رمز\nيمكنك من خلاله تغير كلمة مرور",
  "check_phone_tip2": "يمكنك من خلاله تغير كلمة مرور",
  "send_code": "ارسال",
  "confirm_code": "تأكيد الكود التعريفي",
  "code_sent":
      "لقد قمنا بارسال رمز التأكيد مكون من\n6 رموز علي رقم الموبيل الخاص بك",
  "code_sent_two": "6 رموز على رقم الموبيل الخاص بك ",
  "resend_faild": "لم تستلم رساله بعد؟",
  "send_again": "اعادة الارسال بعد",
  "confirm_new_password": "تاكيد كلمة المرور الجديدة",
  "success_change_password": "تم تغيير كلمة السر بنجاح",
  "success_tip": "لقد تم تغير كلمة السر بنجاح قم بالذهاب ",
  "success_tip_2": "الي تسجيل الدخول مرة اخري",
  "back_to_login": "العودة لتسجيل الدخول",
  "complete_data_to_register": "أكمل البيانات لإنشاء حساب",

  "success_register": "تم انشاء حسابك بنجاح",
  "sucess_register_tip": "يمكنك الان الاستمتاع بخدمات انجو ",
  "sucess_register_tip_two": "بكل سهولة و يسر و الاستفاده بجميع نقاط الشراء",

  /// New Translate ///

  "enter_full_name": "ادخل الاسم الكامل",
  "enter_email": "ادخل البريد الالكتروني",
  "chosse_role": "اختر الدور",
  "enter_password": "ادخل كلمة المرور",
  "enter_confirm_password": "ادخل تأكيد كلمة المرور",

  /// ── Add Patient Step-by-Step ──
  "step": "خطوة",
  "submit": "إرسال",
  "return_to_main": "العودة للرئيسية",
  "filled": "مكتملة",
  "completed": "مكتمل",
  "patient_information": "معلومات المريض",
  "medical_status_history": "الحالة الطبية والتاريخ",
  "media_attachments": "المرفقات والوسائط",
  "administrative_details": "التفاصيل الإدارية",
  "add_new_patient": "إضافة مريض جديد",
  "add_patient": "إضافة مريض",
  "fill_in_the_patient_details_below": "أدخل بيانات المريض بالأسفل",

  /// New App branch translate
  "caredesk_pro": "كير ديسك برو",
  "the_complete_ecosystem_for_modern_healthcare_management_experience_the_future_of_clinic_operations":
      "النظام البيئي المتكامل لإدارة الرعاية الصحية الحديثة. تجربة مستقبل إدارة العيادات.",
  "toggle_sidebar": "تبديل الشريط الجانبي",
  "search_patients_doctors...": "ابحث عن المرضى والأطباء ...",
  "welcome_back": "مرحبا بك",
  "Here's_what's_happening_at_your_clinic_today":
      "اكتشف أحدث الاتجاهات في الرعاية الصحية، وشارك قصص نجاح المرضى، وتعمّق في تحليلات البيانات المتقدمة لاتخاذ قرارات مستنيرة.",
  "export_report": "تصدير التقرير",
  "new_appointment": "حجز موعد جديد",
  "weekly_appointments_trend": "تحليل شامل للاتجاهات الأسبوعية",
  "Mon": "الاثنين",
  "Tue": "الثلاثاء",
  "Wed": "الاربعاء",
  "Thu": "الخميس",
  "Fri": "الجمعة",
  "Sat": "السبت",
  "Sun": "الاحد",
  "clinic_report_exported_successfully_as": "تم تصدير تقرير العيادة بنجاح باسم",
  "total_patients": "إجمالي عدد المرضى",
  "appointments_today": "مواعيد اليوم",
  "total_revenue": "إجمالي الإيرادات",
  "active_doctors": "عدد الأطباء",
  "appointments_in_progress": "المواعيد قيد التنفيذ",
  "total_new_patients": "عدد المرضى الجدد",
  "pending_appointments": "المواعيد المعلقة",
  "completed_appointments": "المواعيد المكتملة",
  "revenue_overview": "نظره عامة على الإيرادات",
  "demographics": "التركيبة السكانية",
  "quick_actions": "الإجراءات السريعة",
  "create_invoice": "إنشاء فاتورة",
  "manage_schedule": "إدارة الجدول",
  "recent_activity": "اخر الانشطة",
  "new_appointment_scheduled": "حجز موعد جديد",
  "appointment_reminder_sent": "تم إرسال تذكير بالموعد",
  "ago": "منذ",
  "select_your_preferred_document_format_to_download_the_comprehensive_clinic_performance_report":
      "اختر تنسيق المستند المفضل لديك لتنزيل تقرير أداء العيادة الشامل.",
  "perfect_for_printing_and_sharing_official_reports":
      "مثالي للطباعة ومشاركة التقارير الرسمية",
  "ideal_for_detailed_custom_data_analysis":
      "مثالي لتحليل البيانات المخصص المفصل",
  "lightweight_format_for_database_imports":
      "تنسيق خفيف للواردات قاعدة البيانات",
  "generating": "جاري التحضير",
  "Exporting": "جاري التصدير",
  "download_report": "تحميل التقرير",
  "report": "التقرير",
  "please_do_not_close_this_window": "الرجاء عدم إغلاق هذه النافذة",
  "arabic": "العربية",
  "english": "الإنجليزية",
  "display_language": "لغة العرض",
  "select_app_language": "اختر لغة التطبيق",
  "language_changed_successfully": "تم تغيير لغة التطبيق بنجاح",
  "dashboard": "لوحة التحكم",
  "patients": "المرضى",
  "schedule": "الجدول",
  "billing": "الفواتير",
  "inventory": "المخزون",
  "appointments": "المواعيد",
  "profile": "الملف الشخصي",
  "settings": "الإعدادات",
  "users": "المستخدمين",
  "roles": "الأدوار",
  "appearance": "المظهر",
  "select_theme_mode": "اختر وضع المظهر للتطبيق",
  "light_mode": "الوضع المضيء",
  "dark_mode": "الوضع المظلم",
  "start_your_journey": "ابدأ رحلتك",
  "register_desc":
      "أنشئ مساحة عمل الرعاية الصحية الاحترافية الخاصة بك في دقائق. انضم إلى آلاف العيادات التي تنمو مع CareDesk.",
  // "create_account": "إنشاء حساب",
  "register_sub_desc": "انضم إلى مجتمعنا وقم بإدارة عيادتك بشكل أفضل.",
  "already_have_account": "لديك حساب بالفعل؟",
  "sign_in": "تسجيل الدخول",
  "display_name": "اسم العرض",
  "login_to_dashboard": "تسجيل الدخول إلى لوحة التحكم",
  "login_sub_desc": "مرحباً بعودتك! من فضلك أدخل تفاصيل حسابك.",
  "forgot_password": "هل نسيت كلمة المرور؟",
  "new_to_caredesk": "جديد في CareDesk؟",
  "activity_new_appointment_detail": "د. سارة مع المريض أحمد علي",
  "todays_appointments": "مواعيد اليوم",
  "view_all": "عرض الكل",
  "confirmed": "مؤكد",
  "pending": "معلق",
  "waiting": "انتظار",
  "recent_patients": "المرضى مؤخراً",
  "see_all": "رؤية الكل",
  "last_visit": "آخر زيارة",
  "doctors_availability": "توفر الأطباء",
  "online_count": "١٢ نشط",
  "cardiologist": "طبيب قلب",
  "neurologist": "طبيب مخ وأعصاب",
  "pediatrician": "طبيب أطفال",
  "general_surgeon": "جراح عام",
  "available": "متاح",
  "busy": "مشغول",
  "on_break": "في استراحة",
  "system_alerts": "تنبيهات النظام",
  "missed_appointments": "مواعيد فائتة",
  "missed_appointments_desc": "فات ٣ مرضى مواعيدهم المقررة اليوم.",
  "pending_invoices_temp": "فواتير معلقة",
  "pending_invoices_desc": "هناك ٥ مدفوعات متأخرة تتطلب الاهتمام.",
  "inventory_low": "مخزون منخفض",
  "inventory_low_desc": "المستلزمات الطبية للغرفة ٤ آخذة في الانخفاض.",
  "pdf_document": "مستند PDF (.pdf)",
  "excel_spreadsheet": "جدول بيانات Excel (.xlsx)",
  "csv_file": "ملف CSV (.csv)",
  "feature_coming_soon": "هذه الميزة ستتوفر قريباً!",
  "patients_directory": "دليل المرضى",
  "new_patient": "مريض جديد",
  // "total_patients": "إجمالي المرضى",
  "all_registered": "جميع المسجلين",
  "active_patients": "المرضى النشطين",
  "currently_active": "نشط حالياً",
  "inactive": "غير نشط",
  "deactivated": "تم تعطيله",
  "new_this_month": "جديد هذا الشهر",
  "vs_last_month_up": "مقارنة بالشهر الماضي ↑",
  "search_by_name_or_phone": "البحث بالاسم أو الهاتف...",
  "all": "الكل",
  "active": "نشط",
  "show_label": "عرض:",
  "patient": "المريض",
  "medical_info": "معلومات طبية",
  "contact": "اتصال",
  "status": "الحالة",
  "actions": "الإجراءات",
  "view_record": "عرض السجل",
  "edit_patient": "تعديل المريض",
  "more_options": "خيارات إضافية",
  "deactivate_patient": "تعطيل المريض",
  "already_inactive": "غير نشط بالفعل",
  "loading_patients": "جاري تحميل المرضى...",
  "no_patients_found": "لم يتم العثور على مرضى",
  "try_adjusting_search_or_filters": "جرّب تعديل البحث أو عوامل التصفية",
  "add_first_patient": "إضافة أول مريض",
  "never_visited": "لم يزر العيادة قط",
  "recent_visit": "زيارة حديثة",
  "no_phone": "بدون هاتف",
  "no_email": "بدون بريد إلكتروني",
  "yrs": "سنة",
  "female": "أنثى",
  "male": "ذكر",
  "unknown": "غير معروف",
  "showing": "عرض",
  "of": "من أصل",
  "results": "نتائج",
  "edit_patient_profile": "تعديل ملف المريض",
  "register_new_patient": "تسجيل مريض جديد",
  "edit_profile": "تعديل الملف",
  "registration": "التسجيل",
  "personal_information": "معلومات شخصية",
  "full_name_required": "الاسم الكامل *",
  "name_required_error": "الاسم مطلوب",
  "phone_number_required": "رقم الهاتف *",
  "phone_required_error": "رقم الهاتف مطلوب",
  "enter_valid_phone": "أدخل رقم هاتف صالح",
  "email_address": "البريد الإلكتروني",
  "invalid_email": "البريد الإلكتروني غير صالح",
  "date_of_birth": "تاريخ الميلاد",
  "medical_background": "الخلفية الطبية",
  "general_medical_history_notes": "التاريخ الطبي العام والملاحظات",
  "chronic_diseases_and_medications": "الأمراض المزمنة والأدوية",
  "medical_files_and_attachments": "الملفات والمرفقات الطبية",
  "address_and_emergency_contact": "العنوان وجهة الاتصال بالطوارئ",
  "home_address": "عنوان المنزل",
  "emergency_contact_name": "اسم جهة الاتصال بالطوارئ",
  "emergency_contact_phone": "هاتف جهة الاتصال بالطوارئ",
  "update_patient_records": "تحديث سجلات المريض",
  "register_new_clinic_patient": "تسجيل مريض جديد بالعيادة",
  "fill_required_fields_desc":
      "ملء جميع الحقول المطلوبة (*). إضافة الأمراض المزمنة والأدوية وفحوصات الملفات يضمن وجود سجلات كاملة.",
  "complete": "اكتمل",
  "gender_not_set": "لم يتم تحديد الجنس",
  "auto_assigned": "تعيين تلقائي",
  "today": "اليوم",
  "blood_type": "فصيلة الدم",
  "chronic_conditions": "الحالات المزمنة",
  "medications": "الأدوية",
  "medical_scans_docs": "الفحوصات والمستندات الطبية",
  "patient_form_tip":
      "نصيحة: أكمل جميع الأقسام للحصول على أفضل تجربة رعاية للمريض.",
  "gender": "الجنس",
  "chronic_diseases_support": "دعم الأمراض المزمنة",
  "chronic_diseases_desc":
      "حدد ما إذا كان هذا المريض يعاني من أي حالات مزمنة طويلة الأمد للمساعدة في تخصيص مخططه الطبي.",
  "has_chronic_disease": "هل يعاني من مرض مزمن؟",
  "select_matching_diseases": "حدد جميع الأمراض المتطابقة:",
  "add_custom_disease_hint": "إضافة مرض مخصص (مثال: مرض حساسية القمح)",
  "current_medications_support": "دعم الأدوية الحالية",
  "current_medications_desc":
      "توثيق الأدوية وجداول الجرعات التي يتناولها المريض حالياً.",
  "currently_taking_medication": "هل يتناول أدوية حالياً؟",
  "no_medications_added_desc":
      "لم يتم إضافة أدوية بعد. اضغط على \"+ إضافة دواء\" أدناه لتسجيل دواء.",
  "add_medication_entry": "إضافة دواء",
  "medication_name": "اسم الدواء",
  "dosage_hint": "الجرعة (مثال: 500 ملغ)",
  "medication_notes_hint": "ملاحظات (مثال: مرتين يومياً)",
  "medical_attachments_upload_system": "نظام رفع المرفقات الطبية",
  "medical_attachments_desc":
      "تحميل التقارير الطبية، أشعة الرنين المغناطيسي، تحاليل الدم المختبرية، الفواتير، والسجلات الورقية (يدعم الصور، PDF، وملفات Excel).",
  "uploading_files_wait": "جاري رفع الملفات، يرجى الانتظار...",
  "click_to_browse_files": "اضغط هنا لتصفح الملفات",
  "supports_file_types": "يدعم: JPEG, PNG, مستند PDF, ملف Excel (XLSX)",
  "selected_files": "الملفات المحددة",
  "yes": "نعم",
  "no": "لا",
  "discard": "تجاهل التغييرات",
  "saving": "جاري الحفظ...",
  "failed_to_pick_files": "فشل في اختيار الملفات",
  "diabetes": "السكري",
  "hypertension": "الضغط",
  "asthma": "الربو",
  "heart_disease": "أمراض القلب",
  "thyroid_disorder": "اضطراب الغدة الدرقية",
  "arthritis": "التهاب المفاصل",
  "other": "أخرى",
  "id": "المعرف",
  "registered": "تاريخ التسجيل",
  "image": "صورة",
  "excel": "إكسل",
  "pdf": "بي دي اف",
  "patient_medical_record": "السجل الطبي للمريض",
  "back_to_list": "العودة للقائمة",
  "active_chart": "ملف نشط",
  "relationship": "العلاقة",
  "family_representative": "ممثل العائلة",
  "medical_summary": "الملخص الطبي",
  "no_chronic_recorded": "لا يوجد أمراض مزمنة مسجلة في هذا الملف.",
  "current_active_medications": "الأدوية النشطة حالياً",
  "no_active_medications": "لا يوجد أدوية نشطة مسجلة.",
  "general_medical_logs": "السجلات الطبية العامة",
  "no_attachments_recorded":
      "لا يوجد فحوصات مخبرية أو ملفات PDF أو فواتير مرفقة.",
  "files_grid": "شبكة الملفات:",
  "download_completed": "اكتمل التنزيل",
  "saved_locally": "تم الحفظ محلياً.",
  "visual_scan_simulation": "محاكاة الفحص البصري نشطة.",
  "click_download_simulation": "النقر على \"تنزيل\" يحاكي جلب الملفات.",
  "document_name": "اسم المستند:",
  "saas_simulation_desc": "محاكاة SaaS: فتح المستند وتعديله وتنزيله مفعّل.",
  "close": "إغلاق",
  "open_download": "فتح/تنزيل",
  "file_downloaded": "تم تنزيل الملف",
  "retrieved_successfully": "تم الاسترجاع بنجاح",
  "visits_history_timeline": "الخط الزمني لتاريخ الزيارات",
  "latest_visit": "آخر زيارة",
  "not_specified": "غير محدد",
  "no_notes": "لا توجد ملاحظات",
  "reason": "السبب",
  "viewer": "المشاهد",
  "users_management": "إدارة المستخدمين",
  "add_new_user": "إضافة مستخدم جديد",
  "no_users_found": "لم يتم العثور على مستخدمين",
  "user": "المستخدم",
  // "email": "البريد",
  "role": "الدور",
  "user_details": "تفاصيل المستخدم",
  "role_level_id": "معرف مستوى الدور",
  "view_details": "عرض التفاصيل",
  "edit_user": "تعديل المستخدم",
  "delete_user": "حذف المستخدم",
  "delete_user_confirm":
      "هل أنت متأكد من رغبتك في حذف @name نهائياً من قائمة الموظفين؟",
  "user_deleted_success": "تم حذف المستخدم بنجاح من سجلات النظام.",
  "create_new_user": "إنشاء مستخدم جديد",
  "create": "إنشاء",
  "basic_information": "المعلومات الأساسية",
  "personal_details_subtitle": "التفاصيل الشخصية ومعلومات الاتصال",
  // "account_settings": "إعدادات الحساب",
  "assign_roles_subtitle": "تعيين الأدوار وصلاحيات الإدارة",
  "discard_changes": "تجاهل التغييرات",
  "save_changes": "حفظ التغييرات",
  // "create_account": "إنشاء حساب",
  "appointments_schedule": "جدول المواعيد",
  "view_calendar": "عرض التقويم",
  // "new_appointment": "موعد جديد",
  "no_appointments_slotted": "لا توجد مواعيد مجدولة",
  "no_appointments_desc": "تتبع استشارات المرضى. احجز موعداً جديداً للبدء.",
  "book_appointment": "حجز موعد",
  "time": "الوقت",
  "doctor": "الطبيب",
  "visit_type": "نوع الزيارة",
  "cancel_appointment": "إلغاء الموعد",
  "complete_appointment": "إكمال الموعد",
  "reschedule_slot": "إعادة جدولة الموعد",
  "remove_log": "حذف السجل",
  "scheduled": "مجدول",
  "consultation": "استشارة",
  "followup": "متابعة",
  "routine": "روتيني",
  "reschedule_appointment": "إعادة جدولة الموعد",
  "book_new_appointment": "حجز موعد جديد",
  "reschedule": "إعادة جدولة",
  "booking": "حجز",
  "select_patient": "اختر المريض",
  "attending_doctor": "الطبيب المعالج",
  "not_assigned": "غير معين",
  "slotted_date": "التاريخ المحدد",
  "slotted_time": "الوقت المحدد",
  "current_status": "الحالة الحالية",
  "conflict_warning":
      "تأكد من عدم وجود تضارب في المواعيد للطبيب المختار في هذا الوقت.",
  "reschedule_banner_title": "إعادة جدولة الموعد السريري",
  "book_banner_title": "حجز استشارة سريرية جديدة",
  "banner_subtitle":
      "حدد نوع الزيارة، وعين الأطباء الأخصائيين، واحجز المواعيد على الفور في الوقت الفعلي.",
  "choose_patient": "اختر المريض *",
  "patient_required": "يرجى اختيار المريض",
  "assign_doctor": "تعيين الطبيب الأخصائي *",
  "doctor_required": "يرجى اختيار الطبيب",
  "appointment_date": "تاريخ الموعد *",
  "choose_date": "اختر التاريخ",
  "time_slot": "الفترة الزمنية *",
  "select_time_slot": "اختر الفترة الزمنية",
  "visit_type_label": "نوع الزيارة *",
  "appointment_status_label": "حالة الموعد *",
  "admin_notes": "ملاحظات إدارية / أسباب الاستشارة",
  "notes_hint": "صف السبب الرئيسي، أو الحساسية المحددة أو التفاصيل...",
  // "discard": "تجاهل",
  // "saving": "جاري الحفظ...",
  "input_error": "خطأ في الإدخال",
  "fields_required": "يرجى إكمال جميع الحقول المطلوبة (*)",
  "emergency": "طوارئ",
  "checkup": "فحص عام",
  "appointments_calendar": "تقويم المواعيد",
  "calendar_view": "عرض التقويم",
  "table_list_view": "عرض القائمة",
  "book_slot": "حجز موعد",
  "month_label": "شهر",
  "week_label": "أسبوع",
  "day_label": "يوم",
  "agenda_slots_booked": "أجندة اليوم المحدد (تم حجز @count مواعيد)",
  "no_consultations_booked": "لا توجد استشارات محجوزة. اضغط للحجز.",
  "with_doctor_at_time": "مع @doctor في @time",
  "mark_as_completed": "تحديد كمكتمل",
  "cancel_slot": "إلغاء الفترة",
  "remove_permanently": "حذف نهائياً",
  "specialist_insights": "رؤى الأخصائيين",
  "total_scheduled": "إجمالي المجدول",
  "confirmed_slots": "الفترات المؤكدة",
  "completed_vis": "الزيارات المكتملة",
  "physician_availability": "توافر الأطباء اليوم",
  // "active": "نشط",
  "on_call": "مناوب",
  "january": "يناير",
  "february": "فبراير",
  "march": "مارس",
  "april": "أبريل",
  "may": "مايو",
  "june": "يونيو",
  "july": "يوليو",
  "august": "أغسطس",
  "september": "سبتمبر",
  "october": "أكتوبر",
  "november": "نوفمبر",
  "december": "ديسمبر",
  "sun": "الأحد",
  "mon": "الاثنين",
  "tue": "الثلاثاء",
  "wed": "الأربعاء",
  "thu": "الخميس",
  "fri": "الجمعة",
  "sat": "السبت",
  "edit_role": "تعديل الدور",
  "define_role": "تعريف الدور",
  "role_identity": "هوية الدور",
  "role_identity_subtitle": "قم بتسمية هذا الدور وإضافة وصف له",
  "role_name": "اسم الدور",
  "role_name_hint": "مثال: طبيب أول",
  "permissions_matrix": "مصفوفة الصلاحيات",
  "permissions_matrix_subtitle": "حدد الإجراءات التي يمكن لهذا الدور القيام بها",
  "save_role": "حفظ الدور",
  "create_role": "إنشاء الدور",
  // "billing": "الفواتير",
  "view_patients": "عرض المرضى",
  "create_patient": "إضافة مريض",
  // "edit_patient": "تعديل مريض",
  "delete_patient": "حذف مريض",
  "view_appointments": "عرض المواعيد",
  "create_appointment": "إنشاء موعد",
  "view_invoices": "عرض الفواتير",
  "edit_invoices": "تعديل الفواتير",
  "roles_permissions": "الأدوار والصلاحيات",
  "define_new_role": "تعريف دور جديد",
  "permissions_count": "عدد الصلاحيات",
  "delete_role": "حذف الدور",
  "delete_role_confirmation": "هل أنت متأكد من أنك تريد حذف الدور \"@role\" بشكل دائم؟",
  "success": "نجاح",
  "role_removed_success": "تم حذف الدور بنجاح.",
  "system_settings": "إعدادات النظام",
  "profile_settings": "إعدادات الملف الشخصي",
  "profile_settings_sub": "إدارة معلوماتك الشخصية وسيرتك الذاتية",
  "account_settings_sub": "تحديث كلمة المرور والجلسات النشطة",
  "general_settings": "الإعدادات العامة",
  "general_settings_sub": "تفاصيل العيادة والتوطين",
  "notifications": "الإشعارات",
  "notifications_sub": "تكوين تنبيهات إشعارات النظام",
  "security": "الأمان",
  "security_sub": "المصادقة الثنائية وسلامة البيانات",
  "theme_settings": "إعدادات المظهر",
  "theme_settings_sub": "المظهر الفاتح والداكن وألوان المظهر",
  "language": "اللغة",
  "language_sub": "اختر لغة الواجهة والمنطقة",
  "system_settings_sub": "التصحيح المتقدم وتكوين النظام",
  "personal_profile": "الملف الشخصي",
  "personal_profile_sub": "إدارة كيفية ظهور تفاصيل ملفك الشخصي العام في نظام النبض.",
  
  "professional_title": "المسمى الوظيفي",
  "account_security": "أمان الحساب",
  "account_security_sub": "تغيير كلمة المرور أو إدارة الجلسات الموثقة الحالية.",
  "current_password": "كلمة المرور الحالية",

  "active_sessions": "الجلسات النشطة",
  "clinic_name": "اسم العيادة",
  "contact_phone": "هاتف التواصل",
  "address": "العنوان",
  "default_timezone": "المنطقة الزمنية الافتراضية",
  "currency_symbol": "رمز العملة",
  "notification_controls": "ضوابط الإشعارات",
  "notification_controls_sub": "قم بتشغيل قنوات إشعارات محددة أو إيقاف تشغيلها وفقًا لتفضيلاتك.",
  "push_notifications": "إشعارات الدفع",
  "push_notifications_sub": "إظهار تنبيهات الدفع الفورية على سطح المكتب والجوال",
  "email_alerts": "تنبيهات البريد الإلكتروني",
  "email_alerts_sub": "تلقي السجلات الطبية وملخصات الورديات اليومية عبر البريد الإلكتروني",
  "appointment_reminders": "تذكيرات المواعيد",
  "appointment_reminders_sub": "إرسال تذكيرات آلية للمرضى قبل 24 ساعة",
  "maintenance_updates": "تحديثات الصيانة",
  "maintenance_updates_sub": "الحصول على إشعارات حول تحديثات النظام المجدولة القادمة",
  "security_safeguards": "ضمانات الأمان",
  "security_safeguards_sub": "قم بتنشيط ضوابط الامتثال الصارمة لحماية بيانات الرعاية الصحية الحيوية.",
  "two_factor_auth": "المصادقة الثنائية (2FA)",
  "two_factor_auth_sub": "يتطلب رمز التحقق OTP أثناء جلسات تسجيل الدخول",
  "biometric_credentials": "بيانات الاعتماد البيومترية",
  "biometric_credentials_sub": "يسمح بإلغاء قفل بصمة الإصبع أو الوجه على المنصات المحمولة المتوافقة",
  "auto_lock_session": "قفل تلقائي للجلسة غير النشطة",
  "auto_lock_session_sub": "قفل الجلسة النشطة تلقائيًا بعد 15 دقيقة من عدم النشاط",
  "theme_customization": "تخصيص المظهر",
  "theme_customization_sub": "تغيير المظهر المرئي للنظام عن طريق تبديل الأنماط أو ألوان التمييز.",
  "display_mode": "وضع العرض",
  "primary_accent_color": "لون التمييز الأساسي",

  "system_default": "النظام الافتراضي",
  "blue": "أزرق",
  "green": "أخضر",
  "purple": "أرجواني",
  "teal": "أزرق مخضر",
  "orange": "برتقالي",
  "system_language": "لغة النظام",
  "system_language_sub": "تبديل عروض النص المترجمة عبر جميع وحدات التنقل.",
  "primary_language": "اللغة الأساسية",

  "french": "الفرنسية (Français)",
  "advanced_developer_settings": "إعدادات المطور المتقدمة",
  "advanced_developer_settings_sub": "ضبط متغيرات النظام الدقيقة، أو تكوين واجهات برمجة تطبيقات الخادم أو تبديل حالات الصيانة.",
  "debug_log_mode": "وضع سجل التصحيح",
  "debug_log_mode_sub": "إخراج تحذيرات مفصلة وسجلات التنفيذ إلى لوحات معلومات المفتش",
  "platform_maintenance_mode": "وضع صيانة المنصة",
  "platform_maintenance_mode_sub": "قفل النظام لموظفي الاستقبال القياسيين، ويسمح للمسؤولين فقط",
  "save_settings": "حفظ الإعدادات",
  "settings_saved_success": "تم حفظ الإعدادات بنجاح!",
  "active_now": "نشط الآن",
  "two_hours_ago": "منذ ساعتين",
  "revoke": "إبطال",
  "login_security": "تسجيل الدخول والأمان",

  "sign_out": "تسجيل الخروج",
  "sign_out_confirm": "هل أنت متأكد أنك تريد تسجيل الخروج من حسابك؟",
  "personal_information_sub": "قم بتحديث تفاصيل ملفك الشخصي وهويتك العامة",
  "your_name": "اسمك",
  "phone_hint": "مثال: +1 234 567 890",
  "professional_bio": "نبذة مهنية",
  "professional_bio_hint": "وصف قصير لدورك وخبرتك",
  "update_profile": "تحديث الملف الشخصي",
  "security_settings": "إعدادات الأمان",
  "security_settings_sub": "إدارة كلمة المرور وأمان الحساب",

};
