const Map<String, String> arEG = {
  "about_app": "عن التطبيق",
  "from_camera": "من الكاميرا",
  "from_gallery": "من المعرض",
  "confirm": "تأكيد",
  "cancel": "إلغاء",
  "enter": "دخول",
  "back": "رجوع",
  "next": "التالي",
  "done": "تم",
  "save": "حفظ",
  "start": "بدء",
  "end": "انهاء",
  "skip": "تخطي",
  "delete": "حذف",
  "edit": "تعديل",
  "add": "إضافة",
  "clear": "مسح",
  "search_anything": "بحث عن أي شيء",
  "search": "بحث",
  "no_data_to_copy": "لا يوجد بيانات للنسخ",
  "show_all": "عرض الكل",
  "?": "؟",
  "illustration_no_connection": "تم قطع الإتصال",
  "illustration_no_connection_details":
      "عذرا تم قطع الاتصال بالإنترنت , تأكد من الاتصال و أعد المحاولة في وقت لاحق",
  "illustration_something_went_wrong": "حدث خطأ ما",
  "illustration_something_went_wrong_details":
      "حدث خطأ ما , تأكد من اتصالك و أعد المحاولة في وقت لاحق",
  "illustration_no_notifications": "لا يوجد إشعارات",
  "illustration_no_notifications_details": "لا يوجد إشعارات حتى الآن",
  "illustration_unknown": "خطأ غير معروف",
  "illustration_unknown_details":
      "حدث خطأ غير معروف , يرجى المحاولة مرة أخرى في وقت لاحق",
  "validate_address": "عفوا لم يتم ادخال عنوان",
  "number_not_empty": "يجب ألا يكون الرقم فارغًا",
  "number_not_correct": "الرجاء إدخال رقم صالح",
  "number_not_minus": "لا يمكن أن يكون الرقم أقل من 1",
  "validate_admin_adjective": "عفوا لم يتم صفه المسؤول",
  "validate_age": "من فضلك أدخل عمر صحيح",
  "validate_age_limit": "يجب أن لا يقل العمر عن 16 سنة",
  "validate_city": "عفوا لم يتم اختيار مدينه",
  "validate_confirm_password": "عفوا كلمة المرور غير متطابقة",
  "validate_date_of_birth": "عفوا لم يتم ادخال تاريخ ميلاد",
  "validate_email": "عفوا لم يتم ادخال بريد مستخدم صحيح",
  "validate_email_2": "من فضلك أدخل بريد إلكتروني صحيح",
  "validate_empty_field":
      "الحقل فارغ. من فضلك تأكد من ملء بيانات الحقل المطلوبة",
  "field_required": "الحقل مطلوب",
  "validate_lang": "عفوا لم يتم اختيار اللغات",
  "validate_language": " يجب على الأقل أن تختار لغة واحدة للمتابعة",
  "validate_message": "عفوا لم يتم ادخال رسالة صحيحة",
  "validate_numeric": "يجب أن تكون البيانات المدخلة أرقام",
  "validate_offered_service": "عفوا لم يتم اختيار الخدمة المقدمة",
  "validate_password": "عفوا لم يتم ادخال كلمة مرور صحيحة",
  "validate_password_length": "يجب ألا تقل كلمة المرور عن 8 أحرف أو أرقام",
  "validate_phone": "عفوا لم يتم ادخال رقم هاتف صحيح",
  "validate_phone_is_real": "! حاول مرة أخرى برقم هاتف صحيح",
  "validate_promo": "عفوا لم يتم ادخال كود صحيح",
  "validate_skills": "عفوا لم يتم اختيار المهارات",
  "validate_username": "عفوا لم يتم ادخال اسم مستخدم صحيح",
  "validate_username_length": "يجب أن يكون اسم المستخدم مكون من أكثر من حرفين",
  "snack_check_ur_connection": "تأكد من اتصالك بالإنترنت",
  "snack_something_went_wrong": "حدث خطأ ما",
  "snack_success": "تم بنجاح",
  "snack_error": "حدث خطأ ما",
  "snack_login_success": "تم تسجيل الدخول بنجاح",
  "snack_logout_success": "تم تسجيل الخروج بنجاح",
  "snack_register_success": "تم التسجيل بنجاح",
  "snack_short_password": "كلمة المرور قصيرة جدا",
  "snack_validate_number": "يجب أن تكون البيانات المدخلة أرقام",
  "success_password": "تم تغيير كلمة المرور بنجاح",
  "success_phone_verify": "تم تفعيل الهاتف بنجاح",
  "success_message_sent": "تم إرسال الرسالة بنجاح",
  "success_username": "تم تغيير اسم المستخدم بنجاح",
  "success_birthday": "تم تغيير تاريخ الميلاد بنجاح",
  "success_image": "تم تغيير الصورة بنجاح",
  "retry": "اعادة المحاولة",

  /// TODO: add new keys
  "ex_bad_request": "خطأ في الطلب",
  "ex_unauthorized": "غير مصرح لك بالوصول",
  "ex_forbidden": "ممنوع",
  "ex_not_found": "غير موجود",
  "ex_method_not_allowed": "الطريقة غير مسموح بها",
  "ex_not_acceptable": "غير مقبول",
  "accept": "قبول",
  "reject": "رفض",
  "accept_trip": "قبول الرحله",
  "reject_trip": "رفض الرحله",
  "ex_request_timeout": "انتهت مهلة الطلب",
  "ex_conflict": "حدث تعارض",
  "ex_internal_Server": "خطأ في الخادم",
  "ex_not_implemented": "لم يتم تنفيذه",
  "ex_bad_gateway": "بوابة سيئة",
  "ex_service_unavailable": "الخدمة غير متوفرة",
  "ex_gateway_timeout": "انتهت مهلة البوابة",
  "ex_unknown": "خطأ غير معروف",
  "ex_network": "خطأ في الشبكة",

  ///todo: add new keys of Anjo
  "login": "تسجيل الدخول",
  "dont_have_account": "ليس لديك حساب ؟",
  "enter_phone_number": "أدخل رقم الهاتف",
  "have_account": "لديك حساب بالفعل ؟",
  "create_account": "إنشاء حساب ",
  "logout": "تسجيل الخروج",
  "change_password": "تغيير كلمة المرور",
  "confirm_password": "تأكيد كلمة المرور",
  "phone_number": "رقم الموبايل",
  "phone": "الهاتف",
  "password": "كلمة المرور",
  "forget_password": "نسيت كلمة المرور ؟",
  "new_password": "كلمة المرور الجديدة",
  "reset_password_tip":
      "ادخل كلمة مرور قوية تحتوي على الاقل \nأحروف و ارقام و رموز",
  "enter_new_password": "أدخل كلمة المرور الجديدة",
  "user_name": "اسم المستخدم",
  "email": "البريد الإلكتروني",
  "register_now": "سجل الآن",
  "new_user": " جديد لدينا ؟",
  "delete_account": "حذف الحساب",
  "account_settings": "إعدادات الحساب",
  "support": "تواصل مع الدعم",
  "about": "عن التطبيق",
  "home": "الرئيسية",
  "privacy_policy": "سياسة الخصوصية",
  "terms_and_conditions": "الشروط و الأحكام",
  "see_more": "عرض الكل",
  "android": "أندرويد",
  "ios": "آيفون",
  "web": "ويب",
  "validate_phone_length": "يجب أن يكون رقم الهاتف مكون من 11 رقم",
  "skip_to": "تخطى",
  "onBoarding_title_1":
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص ",
  "onBoarding_body_1": "خدمة سيارات الإسعاف المجهزة طبيا",
  "onBoarding_title_2":
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص ",
  "onBoarding_body_2": "خدمة جدولة طلب سيارات الإسعاف",
  "onBoarding_title_3":
      "هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص ",
  "onBoarding_body_3": "خدمة التنقل بين المدن",
  "onBoarding_body_4":
      "محتاج تشوف البهجه وتحس بالوان عصريه ووميزه مع دهانات انجو هتحس بكل تفاصيل البهجه اللي بتميز بيتك",
  "login_tips": "ادخل رقم الموبيل الخاص بك لتسجيل الدخول \nاو انشاء حساب جديد",
  "welcome_back": "مرحبا بك مرة اخري",
  "register_tip": "قم انشاء حسابك و استمتع بأفضل خدمات حجز الرحلات",
  "full_name": "الاسم بالكامل",
  "emial": "البريد الالكتروني",
  "complete_register": "اكمال التسجيل",
  "some_questions": " الاسئلة الشائعة ",
  "add_review": "اضافة تقييم ",
  "reset_password": "إسترجاع كلمة المرور",
  "code_verify": "التحقق من الكود",
  "check_phone_tip":
      "أدخل رقم جوال حسابك حتي نرسل إليك رمز\nيمكنك من خلاله تغير كلمة مرور",
  "check_phone_tip2": "يمكنك من خلاله تغير كلمة مرور",
  "send_code": "ارسال",
  "confirm_code": "تأكيد الكود التعريفي",
  "code_sent":
      "لقد قمنا بارسال رمز التأكيد مكون من\n6 رموز علي رقم الموبيل الخاص بك",
  "code_sent_two": "6 رموز على رقم الموبيل الخاص بك ",
  "resend_faild": "لم تستلم رساله بعد؟",
  "send_again": "اعادة الارسال بعد",
  "confirm_new_password": "تاكيد كلمة المرور الجديدة",
  "success_change_password": "تم تغيير كلمة السر بنجاح",
  "success_tip": "لقد تم تغير كلمة السر بنجاح قم بالذهاب ",
  "success_tip_2": "الي تسجيل الدخول مرة اخري",
  "back_to_login": "العودة لتسجيل الدخول",
  "complete_data_to_register": "أكمل البيانات لإنشاء حساب",
  "identification_number": "رقم الهوية",
  "address": "العنوان",
  "car_number": "رقم السيارة",
  "car_license_number": "رقم رخصة القيادة",

  "success_register": "تم انشاء حسابك بنجاح",
  "sucess_register_tip": "يمكنك الان الاستمتاع بخدمات انجو ",
  "sucess_register_tip_two": "بكل سهولة و يسر و الاستفاده بجميع نقاط الشراء",
  "location_access": "السماح للوصول للموقعك؟",
  "location_access_tip": "نطلب منك اذن السماح الوصول الى موقعك للتعرف ",
  "location_access_tip_2": "على اقرب منافذ البيع الخاصة بنا القريبة منك",
  "go_location": "تمكين موقعك الحالى",
  "enter_new_password_tips": "ادخل كلمة مرور قوية تحتوي علي الاقل",
  "enter_new_password_tips_2": "8 احرف و ارقام و رموز",
  "old_password": "كلمة المرور الحالية",
  "save_changes": "حفظ التغييرات",
  "confirm_register_code": "تأكيد رمز انشاء الحساب",
  "verification_code": "رمز التأكيد",
  "register_phone_before": "رقم الجوال مسجل من قبل !",
  "Login_with_password":
      "رقم الجوال الذي أدخلته مسجل من قبل ,قم بإدخال كلمة\n   المرور أو انشئ حساب جديد برقم اخر",
  "welcome": "مرحبا",
  "welcome_text": "اطلب الخدمة التي تريد",
  "select_language": "اختيار اللغه",
  "notifications": "الاشعارات",
  "saved_address": "العناوين المحفوظة",
  "personal_info": "المعلومات الشخصيه",
  "arabic": "العربية",
  "english": "انجليزي",
  "your_trips": "مشاويرك ",
  "technical_support": "الدعم الفني",
  "about_us": "عن التطبيق",
  "rate_the_app": "تقييم التطبيق",
  "global_settings": "الاعدادات العامه",
  "order_ambulance": "طلب سيارة إسعاف",
  "special_ambulance": "إسعاف مخصوص",
  "start_trip": "ابدأ رحلتك",
  "schedule_trip": "جدوله الرحله",
  "validate_invalid_email": "الايميل غير صحيح",
  "date": "التاريخ",
  "time": "الوقت",
  "now": "الآن",
  "You_did_not_choose_date": "لم تقم بأختيار تاريخ",
  "You_did_not_choose_time": "لم تقم بأختيار وقت",
  "save_schedule": "حفظ الجدوله",
  "scheduled": "المجدول",
  "Where_do_you_want_to_go": "إلي اين تريد ان تذهب ؟",
  "skip_now": "تخطي الان",
  "enter_pickup_location": "أبحث عن مكان الانطلاق",
  "where_to": "أبحث عن مكان التوجه",
  "continue": "استمر",
  "pickup_location_on_map": "ابحث عن مكان الانطلاق علي الخريطه",
  "where_to_on_map": "ابحث عن وجهتك علي الخريطه",
  "chose_category_title": "اختر الفئة التي تناسب الحالة الصحية للمريض",
  "chose_the_car_now": "أختار السيارة الان",
  "chose_the_car": "إختيار السيارة",
  "cancel_after": "الغاء بعد",
  "can_cancel_after": "يمكن الغاء الرحلة بعد",
  "will_be_charged_cancel_after":
      "سيتم خصم مبلغ من حسابك في حالة الغاء الرحلة بعد",
  "pay_cash": "الدفع نقدا",
  "enter_amount": "أدخل المبلغ المدفوع",
  "add_comment": "اضف تعليق ",
  "amount_should_pay": "المبلغ المطلوب دفعه",
  "confirm_payment": "تأكيد الدفع",
  "add_trip_rating_title": "اضف تقييم للرحلة",
  "add_trip_rating_subtitle":
      "قم بتقييم هذه الرحله لمعرفة ما مدى رضائك من الرحله ",
  "driver_agreed_to_your_request": "وافق السائق على طلبك",
  "start_now": "ابدا الان",
  "plz_enter_phone": "من فضلك ادخل رقم الموبايل",
  "minutes_for_arrival_to_you": "دقائق للوصول إليك",
  "meters": "متر",
  "hello": "👋 مرحبا",
  "order_service_you_want": "اطلب الخدمة التي تريدها",
  "order_service": "طلب رحلة",
  "among_cities": "رحله مجدوله",
  "Ambulance_next_to_you": "سيارة الرحلات بالقرب منك",
  "my_trips": "رحلاتك ",
  "general_settings": "الاعدادات العامة",
  "rate_app": "قيم التطبيق",

  "cancel_success": "تم الغاء الرحلة بنجاح",
  "cancel_success_message": "تم الغاء الرحلة بنجاح٫ انتظار رحلة اخري",
  "version": "الإصدار",
  "made_with_love_by_xcoders": "Made with ❤ by Xcoders",
  "think_outside_box": "Think outside the box",
  "previous": "السابقة",
  "upcoming": "القادمة",
  "there_is_no_previous_trips": "لا توجد رحلات سابقة",
  "there_is_no_previous_trips_subtitle":
      "لا توجد رحلات سابقة، يمكنك بدء رحلة جديدة مع إسعافي",
  "there_is_no_upcoming_trips": "لا توجد رحلات قادمة",
  "there_is_no_upcoming_trips_subtitle":
      "لا توجد رحلات قادمة، يمكنك بدء رحلة جديدة مع إسعافي",
  "appoint_trip": "احجز رحلة",
  "trip_number": "رقم الرحلة",
  "plz_enter_your_password": "مرحبا بك من جديد",
  "login_by_password_tips": "مرحبا بك من جديد ادخل كلمة المرور للمتابعة",
  "follow": "المتابعه",
  "trip_details": "تفاصيل الرحلة",
  "trip_price": "سعر الرحلة",
  "addresses_details": "تفاصيل العناوين",
  "service_details": "تفاصيل الخدمة",
  "payment_details": "تفاصيل الدفع",
  "rate": "تقيم",
  "reorder": "اعادة الطلب",
  "help": "مساعدة",
  "contact_us": "تواصل معنا",
  "enter_your_message": "ادخل رسالتك",
  "enter_your_name": "ادخل اسمك",
  "enter_your_email": "ادخل بريدك الالكتروني",
  "send": "ارسال",
  "select_destination": "حدد وجهتك",
  "where_are_you_going?": "الي اين تريد ان تذهب ؟",
  "search_of_destionation": "ابحث عن وجهتك",
  "enter_time_trip": "ادخل موعد الرحله",
  "enter_date_trip": "ادخل تاريخ الرحله",
  "trip_schedule": "رحله مجدوله",
  "trip_date": "تاريخ الرحله",
  "trip_time": "موعد الرحله",
  "from": "من",
  "to": "الى",
  "select_time_trip": "حدد موعد الرحله",
  "select_category": "اختار الفئة",
  "all_car_models": "جميع موديلات السيارات ",
  "all_car_years": "جميع سنوات السيارات ",
  "reset_password_done": "تم تغيير كلمة المرور بنجاح",
  "general_rating": "التقييم العام",
  "total_distance": "المسافة الكلية",
  "trips_count": "عدد الرحلات",

  /// -------------- Auth ------------------
  "upload_your_image": "قم برفع صورتك",
  "driving_license_image": "صورة رخصة القيادة",
  "upload_driving_license_image_subtitle":
      "قم برفع صورة واضحة لرخصة القيادة الخاصة بك",
  "car_license_image": "صورة رخصة السيارة",
  "upload_car_license_image_subtitle":
      "قم برفع صورة واضحة لرخصة السيارة الخاصة بك",
  "car_image": "صورة السيارة",
  "upload_car_image_subtitle": "قم برفع صورة واضحة للسيارة الخاصة بك",
  "car_insurance_image": "صورة تأمين السيارة",
  "upload_car_insurance_image_subtitle":
      "قم برفع صورة واضحة لتأمين السيارة الخاصة بك",
  "your_identity_image": "صورة الهوية",
  "upload_your_identity_image_subtitle": "قم برفع صورة واضحة للهوية الخاصة بك",
  "selected_color": "اللون المختار",
  "select_color": "اختر اللون",
  "pick": "اختر",
  "car_color": "لون السيارة",

  /// -------------- Trips ------------------
  "trips_details": "تفاصيل الرحلات",
  "assigned_trips": "الرحلات المعينة",
  "last_trips": "اخر الرحلات",
  "current_trips": "الرحلات الحالية",
  "there_is_no_assinged_trips": "لا توجد رحلات معينة",
  "there_is_no_current_trips": "لا توجد رحلات حالية",
  "there_is_no_last_trips": "لا توجد رحلات سابقة",
  "there_is_no_trips": "لا توجد رحلات الان",
  "there_is_no_trips_subtitle": "لا توجد رحلات الان",
  "there_is_no_assigned_trips_subtitle":
      "لا توجد رحلات معينة، يمكنك بدء رحلة جديدة مع إسعافي",
  "there_is_no_current_trips_subtitle":
      "لا توجد رحلات حالية، يمكنك بدء رحلة جديدة مع إسعافي",
  "there_is_no_last_trips_subtitle":
      "لا توجد رحلات سابقة، يمكنك بدء رحلة جديدة مع إسعافي",
  "accepted_trip": "الرحلة المقبولة",
  "go_to_client": "الذهاب للعميل",
  "go_to_destination": "الذهاب للوجهة",
  "trip_distance": "مسافة الرحلة",
  "trip_duration": "مدة الرحلة",
  "m": "م",
  "km": "كم",
  "am": "ص",
  "pm": "م",
  "no_assigned_trips_for_driver_title":
      "لا يوجد رحلات الأن .. فى انتظار البحث عن رحله مناسبه لك",
  "min": "دقيقة",
  "hr": "ساعة",
  "trip_cost": "تكلفة الرحلة",
  'distance': "المسافة",

  /// -------------- Wallet ------------------
  "wallet_balance": "رصيد المحفظة",
  "current_balance": "الرصيد الحالي",
  "add_balance": "اضافة رصيد",
  "charge_balance": "شحن الرصيد",
  "last_transactions": "اخر العمليات",
  "wallet_transactions": "عمليات المحفظة",
  "waiting_for_driver": " في انتظار السائق.....",
  "trips": "الرحلات",
  "current_trip": "الرحله الحالية",
  "wallet": "المحفظة",
  "assign_trips": "رحلات في انتضار القبول",
  "sec": "ثانية",
  "arrived": "الوصول",
  "add_cancel_reason": "الرجاء اضافة سبب الغاء الرحلة",
  "add_reason": " اضف سبب",
  "select_reason": " اختر سبب",
  "cancel_trip_after": "الغاء الرحله بعد ",
  "general_setting": "الإعدادات العامة",
  "transaction_done_price": "تمت العملية بمبلغ",
  "EGP": "جنيه",
  "EGP_for": "جنيه ل",
  "cash": "نقدي",
  "unknown": "غير معروف",
  "cancel_success_message_with_cost": "تم الغاء الرحلة بنجاح و تم خصم من حسابك",

  /// -------------- Profile ------------------
  "profile": "الملف الشخصي",
  "edit_profile": "المعلومات الشخصيه",
  "profile_updated_successfully": "تم تحديث الملف الشخصي بنجاح",
  "password_updated_successfully": "تم تحديث كلمة المرور بنجاح",
  "edit_your_profile_title": "تعديل الملف الشخصي",

  "you_are_sure_delete_account": "هل انت متأكد من حذب الحساب ",
  "yes_sure": "تأكيد الحذف ",

  /// -------------- Car Selection ------------------
  "select_car_type": "اختر نوع السيارة",
  "car_type": "نوع السيارة",
  "select_car_brand": "اختر ماركة السيارة",
  "car_brand": "ماركة السيارة",
  "select_car_model": "اختر موديل السيارة",
  "car_model": "موديل السيارة",
  "select_car_year": "اختر سنة السيارة",
  "car_year": "سنة السيارة",
  "car_type_not_selected": "لم يتم اختيار نوع السيارة",
  "car_brand_not_selected": "لم يتم اختيار ماركة السيارة",
  "car_model_not_selected": "لم يتم اختيار موديل السيارة",

  /// -------------- Waiting Acceptance ------------------
  "waiting_acceptance": "في انتظار الموافقة",
  "waiting_acceptance_description":
      "في انتظار الموافقة من المالك على الطلب الخاص بك",

  /// -------------- Block Order ------------------
  "block_order": "حظر الطلب",
  "block_order_description": "لقد تم حظر الطلب الخاص بك من قبل المالك",
  "you_blocked": "لقد تم حظرك",
  "you_blocked_description": "لقد تم حظرك من قبل المالك",

  /// ---------------- driver state -----------------
  "status_changed_succssfully": "تم تغيير الحالة بنجاح",

  /// ---------------- profile ------------------
  "no_data_title": "لا توجد بيانات",
  "no_data_subtitle": "لا توجد بيانات حتى الآن",
  "password_confirm": "تأكيد كلمة المرور",
  "register": "انشاء حساب",

  /// New Translate ///
  /// 
  "enter_full_name":"ادخل الاسم الكامل",
  "enter_email":"ادخل البريد الالكتروني",
  "chosse_role":"اختر الدور",
  "enter_password":"ادخل كلمة المرور",
  "enter_confirm_password":"ادخل تأكيد كلمة المرور",

};
