const Map<String, String> enUS = {
  "about_app": "About the application",
  "from_camera": "From Camera",
  "from_gallery": "From Gallery",
  "confirm": "Confirm",
  "cancel": "Cancel",
  "enter": "Enter",
  "back": "Back",
  "next": "Next",
  "done": "Done",
  "save": "Save",
  "start": "Start",
  "skip": "Skip",
  "delete": "Delete",
  "edit": "Edit",
  "add": "Add",
  "clear": "Clear",
  "search_anything": "Search anything",
  "search": "Search",
  "no_data_to_copy": "No data to copy",
  "show_all": "Show All",
  "?": "؟",
  "illustration_no_connection": "The connection has been cut off",
  "illustration_no_connection_details":
      "Sorry,internet connection has been cut,be sure to connect and try at a later time",
  "illustration_something_went_wrong": "An error occurred",
  "illustration_something_went_wrong_details":
      "An error occurred,make sure you contact and try at a later time",
  "illustration_no_notifications": "No notifications",
  "illustration_no_notifications_details": "No notifications yet",
  "illustration_unknown": "Unknown error",
  "illustration_unknown_details":
      "There was an unknown error,please try again later",
  "validate_address": "Sorry,no address has been entered",
  "validate_admin_adjective": "Sorry,the official was not described",
  "validate_age": "Please enter a right life",
  "validate_age_limit": "It should not be less than 16 years old",
  "validate_city": "Sorry,a city was not chosen",
  "validate_confirm_password": "Sorry,the password is not identical",
  "validate_date_of_birth": "Sorry,the date of birth was not entered",
  "validate_email": "Sorry,a correct user mail was not inserted",
  "validate_email_2": "Please enter a correct email",
  "validate_empty_field":
      "The field is empty. Please make sure to fill the required field data",
  "validate_lang": "Sorry,the languages were not chosen",
  "validate_language": "At least you must choose one language to follow",
  "validate_message": "Sorry,the correct message was not entered",
  "validate_numeric": "The data entered must be numbers",
  "validate_offered_service": "Sorry,the service provided has not been chosen",
  "validate_password": "Sorry,the correct password has not been entered",
  "validate_password_length":
      "The password should not be less than 8 letters or numbers",
  "validate_phone": "Sorry,the correct phone number has not been entered",
  "validate_phone_is_real": "! Try again with a correct phone number",
  "validate_promo": "Sorry,the correct code has not been entered",
  "validate_skills": "Sorry,the skills have not been chosen",
  "validate_username": "Sorry,the name of a correct user has not been entered",
  "validate_username_length":
      "The username must be made up of more than two letters",
  "snack_check_ur_connection": "Check your internet connection",
  "snack_something_went_wrong": "Something went wrong",
  "snack_success": "Done successfully",
  "snack_error": "apparently, an error occurred",
  "snack_login_success": "Login successfully",
  "snack_logout_success": "Logout successfully",
  "snack_register_success": "Registration successfully",
  "snack_short_password":
      "The password should not be less than 6 letters or numbers",
  "snack_validate_number": "Please enter a correct number",
  "success_password": "Password changed successfully",
  "success_phone_verify": "Phone number verified successfully",
  "success_message_sent": "Message sent successfully",
  "success_username": "UserName updated successfully",
  "success_birthday": "Birthday updated successfully",
  "success_image": "Image updated successfully",
  "login": "Login",
  "dont_have_account": "Don't have an account?",
  "enter_phone_number": "Enter phone number",
  "have_account": "Already have an account?",
  "create_account": "Create an account",
  "logout": "Logout",
  "change_password": "Change password",
  "confirm_password": "Confirm password",
  "phone_number": "Phone number",
  "phone": "Phone",
  "password": "Password",
  "forget_password": "Forgot password?",
  "new_password": "New password",
  "reset_password_tip":
      "Enter a strong password containing \nat least letters, numbers, and symbols.",
  "enter_new_password": "Enter new password",
  "user_name": "Username",
  "email": "Email",
  "register_now": "Register now",
  "new_user": "New user?",
  "delete_account": "Delete account",
  "account_settings": "Account settings",
  "support": "Contact support",
  "about": "About",
  "home": "Home",
  "privacy_policy": "Privacy policy",
  "terms_and_conditions": "Terms and conditions",
  "see_more": "See more",
  "android": "Android",
  "ios": "iOS",
  "web": "Web",
  "validate_phone_length": "Phone number must be 11 digits",
  "skip_to": "Skip to",
  "onBoarding_title_1": "Discover the best products and paint colors",
  "onBoarding_body_1":
      "This text is an example that can be replaced in the same space. It has been generated from an Arabic text generator, where you can generate similar text.",
  "onBoarding_title_2": "Discover our nearest outlets",
  "onBoarding_body_2":
      "This text is an example that can be replaced in the same space. It has been generated from an Arabic text generator, where you can generate similar text.",
  "onBoarding_title_3": "Earn points and redeem them for cash prizes",
  "onBoarding_body_3":
      "This text is an example that can be replaced in the same space. It has been generated from an Arabic text generator, where you can generate similar text.",
  "weight": "Weight",
  "section": "Section",
  "new": "New",
  "all_products": "All products",
  "last_news": "Latest news",
  "last_products": "Latest products",
  "sections": "Sections",
  "all_news": "All news",
  "welcome": "Welcome to the Anjo app",
  "login_tips": "Enter your mobile number and password",
  "welcome_back": "Welcome back",
  "register_tip": "Create your account and enjoy the best paints and colors",
  "full_name": "Full name",
  "complete_register": "Complete",
  "product_details": "Product details",
  "details": "Details",
  "ratings": "Ratings",
  "product_description": "Product description",
  "product_feature": "Product features",
  "usage_way": "Usage way",
  "similar_products": "Similar products",
  "five_star": "5 stars",
  "four_star": "4 stars",
  "three_star": "3 stars",
  "two_star": "2 stars",
  "one_star": "1 star",
  "add_review": "Add a review",
  "reset_password": "Reset password",
  "check_phone_tip":
      "Enter your account mobile number \nto receive a code for password reset",
  "check_phone_tip2": "You can reset your password through this code",
  "send_code": "Send",
  "confirm_code": "Confirm recovery code",
  "code_sent":
      "We have sent a confirmation code consisting of \n6 digits to your mobile number",
  "code_sent_two": "6 digits to your mobile number",
  "resend_faild": "Haven't received a message yet?",
  "send_again": "Resend",
  "confirm_new_password": "Confirm new password",
  "success_change_password": "Password changed successfully",
  "success_tip":
      "Your password has been successfully changed. Please go back to",
  "success_tip_2": "the login page",
  "back_to_login": "Back to login",
  "region": "Region",
  "chosse_code": "Lawsuit code (optional)",
  "city": "City",
  "governate": "Governorate",
  "success_register": "Your account has been successfully created",
  "sucess_register_tip":
      "Now you can enjoy Anjo's services easily and benefit from all the purchase points",
  "sucess_register_tip_two": "Location access",
  "location_access": "Allow access to your location?",
  "location_access_tip":
      "We request your permission to access your location to identify the nearest sales outlets",
  "location_access_tip_2": "near you",
  "go_location": "Enable your current location",
  "enter_new_password_tips": "Enter a strong password containing at least",
  "enter_new_password_tips_2": "8 characters, numbers, and symbols",
  "old_password": "Current password",
  "save_changes": "Save changes",
  "confirm_register_code": "Confirm registration code",
  "verification_code": "Verification code",
  "register_phone_before": "Mobile number is already registered!",
  "Login_with_password":
      "The mobile number you entered is already registered. Please enter \nyour password or create a new account with another number",
  "government_names": "Governments",
  "city_names": "Cities",
  "success_register_account": "Your account has been successfully created",
  "success_register_account_tip":
      "Now you can enjoy Anjo's services easily and benefit from all the purchase points",
  "rate_product": "Rate the product",
  "success_register_account_tip_2":
      "every time you buy from Anjo products or send an invitation to your friends",
  "Profile": "Profile",
  "my_profile": "My profile",
  "my_password": "My password",
  "places_sale": "Sales outlets",
  "notifications": "Notifications",
  "invite_friends": "Invite a friend",
  "help_center": "Help center",
  "exit": "Exit",
  "government": "Government",
  "nearby_places": "Nearby places",
  "search_of_places": "Search by location",
  "phone : ": "Phone: ",
  "rate_experience": "Rate your experience with the product",
  "rate_experience_hint": "Help us improve our products by rating us",
  "add_comment": "Add a comment",
  "cancle": "Cancel",
  "search_tips": "Search",
  "my_points": "My points",
  "my_current_points": "Your current points balance",
  "help_center_description": "Tell us how we can \nhelp you?",
  "Search_here": "Search here",
  "or_contact_by": "Or contact via",
  "mobile : ": "Mobile: ",
  "whatapp_number : ": "WhatsApp number: ",
  "some_quetions": "Some common questions",
  "Points": "Points",
  "transactions": "Transactions",
  "success_get_gift":
      "Congratulations! You have successfully received the gift",
  "success_get_gift_tip":
      "You have successfully received the gift in exchange for 220 points\n. The management will contact you \nsoon to arrange for gift collection",
  "back_to_main": "Back to main",
  "success_get_points": "Congratulations! You have earned 25 points",
  "success_get_points_tip":
      "You have earned 25 points for your recent product purchase.\n You can collect points each time you buy\n Anjo products or send invitations to your friends",
  "go_to_points": "Go to My Points",
  "sure_place_sale": "Outlet confirmation",
  "sure_place_sale_tip":
      "Congratulations! The purchase has been confirmed by the outlet, and your points have been converted into points balance",
  "section_gifts": "Gift list",
  "empty_search": "Sorry, no search results found!",
  "favorite": "Favorites",
  "sorry_empty_favourite": "Sorry, there are no favorite paints!",
  "points": "Points",
  "profile": "Profile",
  "anjo_presents": "Anjo presents",
  "no_points_title": "Sorry, you have no points in your wallet",
  "no_points_sub_title": "You can earn points by",
  "inputs_scan": "Choose the product input method",
  "scan": "Scan the barcode",
  "inputs_code": "Enter the code manually",
  "inputs_code_tip": "Enter the product code manually",
  "code_product": "Product code",
  "code_product_hint": "Enter the product code",
  "name_sale": "Outlet name",
  "inputs_name_sale": "Enter the outlet name",
  "add_product": "Add more",
  "sure_operation": "Confirm operation",
  "region_names": "Regions",
  " snack_login_success": "Logged in successfully",
  "show_all_transaction": "Show all transactions",
  "Texture": "Texture",
  "per_capita_rate": "Per capita rate",
  "coverage_rate": "Coverage rate",
  "dry_time": "Dry time",
  "validity": "Validity",
  "available_packages": "Available packages",
  "add_product_success": "Added to favorites successfully",
  "remove_product_success": "Removed from favorites successfully",
  "want_sign_out": "Do you want to sign out?",
  "cant_back": "You can't go back",
  "sure": "Sure",
  "no": "No",
  "are_you_sure_you_want_to_leave": "Are you sure you want to leave?",
  "agree": "Agree",
  "sorry_not_found_rating": "No ratings found for this product",
  "add_review_success": "Review added successfully",
  "sign_scan_qr": "QR CODE registration",
  "plase_the_qr_code_in_the_area": "Please place the camera on the QR",
  "scanning_will_be_automatically": "The scan process will be automatic",
  "scan_error": "Sorry, the QR you entered is incorrect",
  "retry": "Retry",
  "send_code_to_invite_friends":
      "Download the Anjo app and use the invitation code to earn points and gifts",
  "code_invite": "Invitation code",
  "select_your_location": "Select your location",
  "your_current_location": "Your current location",
  "state": "Country",
  "province": "Governorate",
  "district": "District",
  "enter_state": "Enter country",
  "enter_city": "Enter governorate",
  "enter_region": "Enter district",
  "zone": "Zone",
  "street": "Street",
  "lang": "Language",
  "choose_lang": "Choose language",
  "please_choose_lang": "Please choose the language",
  "arabic": "Arabic",
  "english": "English",
  "reset_password_done": "Password reset successfully",
  'point': "Point",
  "news_details": "News details",
  "price": "price",
  "no_points": "No points",
  "0 point": "0 Point",
  "no_transaction_title": "Sorry, there are no transactions",
  "no_transaction_sub_title": "You can earn points by purchasing products",
  "no_similar_product_title": "Sorry, there are no similar products",
  "port_location": "Branch Location",
  "description : ": "desc : ",
  "field_required": "Field Required",
  "points : ": "points : ",
  "product_name": "Product name",
  "expire_time": "Expire time",
  "pending": "Pending",
  "apply_buy": "Apply for purchase",
  "accept": "Accept",
  "reject": "Reject",
  "you_are_sure_delete_account":
      "Are you sure you want to delete your account?",
  "delete_account_tip": "",
  "yes_sure": "Yes, sure",
  "minutes_for_arrival_to_you": "Minutes for arrival to you",
  "meters": "Meters",
  "hello": "👋 Hello",
  "order_service_you_want": "Order the service you want",
  "order_service": "Order service",
  "among_cities": "Among cities",
  "Ambulance_next_to_you": "Ambulance next to you",
  "medical_trips": "Medical trips",
  "general_settings": "General settings",
  "technical_support": "Technical support",
  "rate_app": "Rate the app",
  "version": "Version",
  "made_with_love_by_xcoders": "Made with ❤ by Xcoders",
  "think_outside_box": "Think outside the box",
  "previous": "Previous",
  "upcoming": "upcoming",
  "there_is_no_previous_trips": "There is no previous trips",
  "there_is_no_previous_trips_subtitle":
      "You can start a new trip by clicking on the button below",
  "there_is_no_upcoming_trips": "There is no upcoming trips",
  "there_is_no_upcoming_trips_subtitle":
      "You can start a new trip by clicking on the button below",
  "appoint_trip": "Appoint a trip",
  "trip_number": "Trip number",
  "started": "Started",
  "ended": "Ended",
  "arrived": "Arrived",
  "cancelled_by_driver": "Cancelled by driver",
  "cancelled": "Cancelled",
  "refused": "Refused",
  "trip_details": "Trip details",
  "trip_price": "Trip price",
  "addresses_details": "Addresses details",
  "service_details": "Service details",
  "payment_details": "Payment details",
  "rate": "Rate",
  "reorder": "Reorder",
  "car_details": "Car details",
  "price_include_service": "Price include service",
  "help": "Help",

  "contact_us": "Contact us",
  "enter_your_message": "Enter your message",
  "enter_your_name": "Enter your name",
  "enter_your_email": "Enter your email",
  "send": "Send",


  /// -------------- Wallet ------------------
  "wallet_balance": "Wallet balance",
  "current_balance": "Current balance",
  "add_balance": "Add balance",
  "charge_balance": "Charge balance",
  "last_transactions": "Last transactions",
  "wallet_transactions": "Wallet transactions",

};
