const Map<String, String> enUS = {
  "about_app": "About the application",
  "from_camera": "From Camera",
  "from_gallery": "From Gallery",
  "confirm": "Confirm",
  "cancel": "Cancel",
  "enter": "Enter",
  "back": "Back",
  "next": "Next",
  "done": "Done",
  "save": "Save",
  "start": "Start",
  "skip": "Skip",
  "delete": "Delete",
  "edit": "Edit",
  "add": "Add",
  "clear": "Clear",
  "search_anything": "Search anything",
  "search": "Search",
  "no_data_to_copy": "No data to copy",
  "show_all": "Show All",
  "?": "؟",
  "internet_connection_problem":
      "There's a problem with your internet connection. Please try again.",
  "try_again": "Try Again",
  "connected": "Connected",
  "internet_restored": "Internet connection restored.",
  "illustration_no_connection": "The connection has been cut off",
  "illustration_no_connection_details":
      "Sorry,internet connection has been cut,be sure to connect and try at a later time",
  "illustration_something_went_wrong": "An error occurred",
  "illustration_something_went_wrong_details":
      "An error occurred,make sure you contact and try at a later time",
  "illustration_no_notifications": "No notifications",
  "illustration_no_notifications_details": "No notifications yet",
  "illustration_unknown": "Unknown error",
  "illustration_unknown_details":
      "There was an unknown error,please try again later",
  "validate_address": "Sorry,no address has been entered",
  "validate_admin_adjective": "Sorry,the official was not described",
  "validate_age": "Please enter a right life",
  "validate_age_limit": "It should not be less than 16 years old",
  "validate_city": "Sorry,a city was not chosen",
  "validate_confirm_password": "Sorry,the password is not identical",
  "validate_date_of_birth": "Sorry,the date of birth was not entered",
  "validate_email": "Sorry,a correct user mail was not inserted",
  "validate_email_2": "Please enter a correct email",
  "validate_empty_field":
      "The field is empty. Please make sure to fill the required field data",
  "validate_lang": "Sorry,the languages were not chosen",
  "validate_language": "At least you must choose one language to follow",
  "validate_message": "Sorry,the correct message was not entered",
  "validate_numeric": "The data entered must be numbers",
  "validate_offered_service": "Sorry,the service provided has not been chosen",
  "validate_password": "Sorry,the correct password has not been entered",
  "validate_password_length":
      "The password should not be less than 8 letters or numbers",
  "validate_phone": "Sorry,the correct phone number has not been entered",
  "validate_phone_is_real": "! Try again with a correct phone number",
  "validate_promo": "Sorry,the correct code has not been entered",
  "validate_skills": "Sorry,the skills have not been chosen",
  "validate_username": "Sorry,the name of a correct user has not been entered",
  "validate_username_length":
      "The username must be made up of more than two letters",
  "snack_check_ur_connection": "Check your internet connection",
  "snack_something_went_wrong": "Something went wrong",
  "snack_success": "Done successfully",
  "snack_error": "apparently, an error occurred",
  "snack_login_success": "Login successfully",
  "snack_logout_success": "Logout successfully",
  "snack_register_success": "Registration successfully",
  "snack_short_password":
      "The password should not be less than 6 letters or numbers",
  "snack_validate_number": "Please enter a correct number",
  "success_password": "Password changed successfully",
  "success_phone_verify": "Phone number verified successfully",
  "success_message_sent": "Message sent successfully",
  "success_username": "UserName updated successfully",
  "success_birthday": "Birthday updated successfully",
  "success_image": "Image updated successfully",
  "login": "Login",
  "dont_have_account": "Don't have an account?",
  "enter_phone_number": "Enter phone number",
  "have_account": "Already have an account?",
  "create_account": "Create an account",
  "logout": "Logout",
  "change_password": "Change password",
  "confirm_password": "Confirm password",
  "phone_number": "Phone number",
  "phone": "Phone",
  "password": "Password",
  "forget_password": "Forgot password?",
  "new_password": "New password",
  "reset_password_tip":
      "Enter a strong password containing \nat least letters, numbers, and symbols.",
  "enter_new_password": "Enter new password",
  "user_name": "Username",
  "email": "Email",
  "register_now": "Register now",
  "new_user": "New user?",
  "delete_account": "Delete account",
  "account_settings": "Account settings",
  "support": "Contact support",
  "about": "About",
  "home": "Home",
  "privacy_policy": "Privacy policy",
  "terms_and_conditions": "Terms and conditions",
  "see_more": "See more",
  "android": "Android",
  "ios": "iOS",
  "web": "Web",
  "validate_phone_length": "Phone number must be 11 digits",
  "skip_to": "Skip to",
  "onBoarding_title_1": "Discover the best products and paint colors",
  "onBoarding_body_1":
      "This text is an example that can be replaced in the same space. It has been generated from an Arabic text generator, where you can generate similar text.",
  "onBoarding_title_2": "Discover our nearest outlets",
  "onBoarding_body_2":
      "This text is an example that can be replaced in the same space. It has been generated from an Arabic text generator, where you can generate similar text.",
  "onBoarding_title_3": "Earn points and redeem them for cash prizes",
  "onBoarding_body_3":
      "This text is an example that can be replaced in the same space. It has been generated from an Arabic text generator, where you can generate similar text.",
  "weight": "Weight",
  "section": "Section",
  "new": "New",
  "all_products": "All products",
  "last_news": "Latest news",
  "last_products": "Latest products",
  "sections": "Sections",
  "all_news": "All news",
  "welcome": "Welcome to the Anjo app",
  "login_tips": "Enter your mobile number and password",
  "welcome_back": "Welcome back",
  "register_tip": "Create your account and enjoy the best paints and colors",
  "full_name": "Full name",
  "complete_register": "Complete",
  "product_details": "Product details",
  "details": "Details",
  "ratings": "Ratings",
  "product_description": "Product description",
  "product_feature": "Product features",
  "usage_way": "Usage way",
  "similar_products": "Similar products",
  "five_star": "5 stars",
  "four_star": "4 stars",
  "three_star": "3 stars",
  "two_star": "2 stars",
  "one_star": "1 star",
  "add_review": "Add a review",
  "reset_password": "Reset password",
  "check_phone_tip":
      "Enter your account mobile number \nto receive a code for password reset",
  "check_phone_tip2": "You can reset your password through this code",
  "send_code": "Send",
  "confirm_code": "Confirm recovery code",
  "code_sent":
      "We have sent a confirmation code consisting of \n6 digits to your mobile number",
  "code_sent_two": "6 digits to your mobile number",
  "resend_faild": "Haven't received a message yet?",
  "send_again": "Resend",
  "confirm_new_password": "Confirm new password",
  "success_change_password": "Password changed successfully",
  "success_tip":
      "Your password has been successfully changed. Please go back to",
  "success_tip_2": "the login page",
  "back_to_login": "Back to login",
  "region": "Region",
  "chosse_code": "Lawsuit code (optional)",
  "city": "City",
  "governate": "Governorate",
  "success_register": "Your account has been successfully created",
  "sucess_register_tip":
      "Now you can enjoy Anjo's services easily and benefit from all the purchase points",
  "sucess_register_tip_two": "Location access",
  "location_access": "Allow access to your location?",
  "location_access_tip":
      "We request your permission to access your location to identify the nearest sales outlets",
  "location_access_tip_2": "near you",
  "go_location": "Enable your current location",
  "enter_new_password_tips": "Enter a strong password containing at least",
  "enter_new_password_tips_2": "8 characters, numbers, and symbols",
  "old_password": "Current password",
  "save_changes": "Save changes",
  "confirm_register_code": "Confirm registration code",
  "verification_code": "Verification code",
  "register_phone_before": "Mobile number is already registered!",
  "Login_with_password":
      "The mobile number you entered is already registered. Please enter \nyour password or create a new account with another number",
  "government_names": "Governments",
  "city_names": "Cities",
  "success_register_account": "Your account has been successfully created",
  "success_register_account_tip":
      "Now you can enjoy Anjo's services easily and benefit from all the purchase points",
  "rate_product": "Rate the product",
  "success_register_account_tip_2":
      "every time you buy from Anjo products or send an invitation to your friends",
  "Profile": "Profile",
  "my_profile": "My profile",
  "my_password": "My password",
  "places_sale": "Sales outlets",
  "notifications": "Notifications",
  "invite_friends": "Invite a friend",
  "help_center": "Help center",
  "exit": "Exit",
  "government": "Government",
  "nearby_places": "Nearby places",
  "search_of_places": "Search by location",
  "phone : ": "Phone: ",
  "rate_experience": "Rate your experience with the product",
  "rate_experience_hint": "Help us improve our products by rating us",
  "add_comment": "Add a comment",
  "cancle": "Cancel",
  "search_tips": "Search",
  "my_points": "My points",
  "my_current_points": "Your current points balance",
  "help_center_description": "Tell us how we can \nhelp you?",
  "Search_here": "Search here",
  "or_contact_by": "Or contact via",
  "mobile : ": "Mobile: ",
  "whatapp_number : ": "WhatsApp number: ",
  "some_quetions": "Some common questions",
  "Points": "Points",
  "transactions": "Transactions",
  "success_get_gift":
      "Congratulations! You have successfully received the gift",
  "success_get_gift_tip":
      "You have successfully received the gift in exchange for 220 points\n. The management will contact you \nsoon to arrange for gift collection",
  "back_to_main": "Back to main",
  "success_get_points": "Congratulations! You have earned 25 points",
  "success_get_points_tip":
      "You have earned 25 points for your recent product purchase.\n You can collect points each time you buy\n Anjo products or send invitations to your friends",
  "go_to_points": "Go to My Points",
  "sure_place_sale": "Outlet confirmation",
  "sure_place_sale_tip":
      "Congratulations! The purchase has been confirmed by the outlet, and your points have been converted into points balance",
  "section_gifts": "Gift list",
  "empty_search": "Sorry, no search results found!",
  "favorite": "Favorites",
  "sorry_empty_favourite": "Sorry, there are no favorite paints!",
  "points": "Points",
  "profile": "Profile",
  "anjo_presents": "Anjo presents",
  "no_points_title": "Sorry, you have no points in your wallet",
  "no_points_sub_title": "You can earn points by",
  "inputs_scan": "Choose the product input method",
  "scan": "Scan the barcode",
  "inputs_code": "Enter the code manually",
  "inputs_code_tip": "Enter the product code manually",
  "code_product": "Product code",
  "code_product_hint": "Enter the product code",
  "name_sale": "Outlet name",
  "inputs_name_sale": "Enter the outlet name",
  "add_product": "Add more",
  "sure_operation": "Confirm operation",
  "region_names": "Regions",
  " snack_login_success": "Logged in successfully",
  "show_all_transaction": "Show all transactions",
  "Texture": "Texture",
  "per_capita_rate": "Per capita rate",
  "coverage_rate": "Coverage rate",
  "dry_time": "Dry time",
  "validity": "Validity",
  "available_packages": "Available packages",
  "add_product_success": "Added to favorites successfully",
  "remove_product_success": "Removed from favorites successfully",
  "want_sign_out": "Do you want to sign out?",
  "cant_back": "You can't go back",
  "sure": "Sure",
  "no": "No",
  "are_you_sure_you_want_to_leave": "Are you sure you want to leave?",
  "agree": "Agree",
  "sorry_not_found_rating": "No ratings found for this product",
  "add_review_success": "Review added successfully",
  "sign_scan_qr": "QR CODE registration",
  "plase_the_qr_code_in_the_area": "Please place the camera on the QR",
  "scanning_will_be_automatically": "The scan process will be automatic",
  "scan_error": "Sorry, the QR you entered is incorrect",
  "retry": "Retry",
  "send_code_to_invite_friends":
      "Download the Anjo app and use the invitation code to earn points and gifts",
  "code_invite": "Invitation code",
  "select_your_location": "Select your location",
  "your_current_location": "Your current location",
  "state": "Country",
  "province": "Governorate",
  "district": "District",
  "enter_state": "Enter country",
  "enter_city": "Enter governorate",
  "enter_region": "Enter district",
  "zone": "Zone",
  "street": "Street",
  "lang": "Language",
  "choose_lang": "Choose language",
  "please_choose_lang": "Please choose the language",
  "arabic": "Arabic",
  "english": "English",
  "reset_password_done": "Password reset successfully",
  'point': "Point",
  "news_details": "News details",
  "price": "price",
  "no_points": "No points",
  "0 point": "0 Point",
  "no_transaction_title": "Sorry, there are no transactions",
  "no_transaction_sub_title": "You can earn points by purchasing products",
  "no_similar_product_title": "Sorry, there are no similar products",
  "port_location": "Branch Location",
  "description : ": "desc : ",
  "field_required": "Field Required",
  "points : ": "points : ",
  "product_name": "Product name",
  "expire_time": "Expire time",
  "pending": "Pending",
  "apply_buy": "Apply for purchase",
  "accept": "Accept",
  "reject": "Reject",
  "you_are_sure_delete_account":
      "Are you sure you want to delete your account?",
  "delete_account_tip": "",
  "yes_sure": "Yes, sure",
  "minutes_for_arrival_to_you": "Minutes for arrival to you",
  "meters": "Meters",
  "hello": "👋 Hello",
  "order_service_you_want": "Order the service you want",
  "order_service": "Order service",
  "among_cities": "Among cities",
  "Ambulance_next_to_you": "Ambulance next to you",
  "medical_trips": "Medical trips",
  "general_settings": "General settings",
  "technical_support": "Technical support",
  "rate_app": "Rate the app",
  "version": "Version",
  "made_with_love_by_xcoders": "Made with ❤ by Xcoders",
  "think_outside_box": "Think outside the box",
  "previous": "Previous",
  "upcoming": "upcoming",
  "there_is_no_previous_trips": "There is no previous trips",
  "there_is_no_previous_trips_subtitle":
      "You can start a new trip by clicking on the button below",
  "there_is_no_upcoming_trips": "There is no upcoming trips",
  "there_is_no_upcoming_trips_subtitle":
      "You can start a new trip by clicking on the button below",
  "appoint_trip": "Appoint a trip",
  "trip_number": "Trip number",
  "started": "Started",
  "ended": "Ended",
  "arrived": "Arrived",
  "cancelled_by_driver": "Cancelled by driver",
  "cancelled": "Cancelled",
  "refused": "Refused",
  "trip_details": "Trip details",
  "trip_price": "Trip price",
  "addresses_details": "Addresses details",
  "service_details": "Service details",
  "payment_details": "Payment details",
  "rate": "Rate",
  "reorder": "Reorder",
  "car_details": "Car details",
  "price_include_service": "Price include service",
  "help": "Help",

  "contact_us": "Contact us",
  "enter_your_message": "Enter your message",
  "enter_your_name": "Enter your name",
  "enter_your_email": "Enter your email",
  "send": "Send",

  /// -------------- Wallet ------------------
  "wallet_balance": "Wallet balance",
  "current_balance": "Current balance",
  "add_balance": "Add balance",
  "charge_balance": "Charge balance",
  "last_transactions": "Last transactions",
  "wallet_transactions": "Wallet transactions",

  /// ── Add Patient Step-by-Step ──
  "step": "Step",
  "submit": "Submit",
  "return_to_main": "Return to Main",
  "filled": "Filled",
  "completed": "Completed",
  "patient_information": "Patient Information",
  "medical_status_history": "Medical Status & History",
  "media_attachments": "Media Attachments",
  "administrative_details": "Administrative Details",
  "add_new_patient": "Add New Patient",
  "fill_in_the_patient_details_below": "Fill in the patient details below",
  "display_language": "Display Language",
  "select_app_language": "Select Application Language",
  "language_changed_successfully": "Application language updated successfully!",
  "appearance": "Appearance",
  "select_theme_mode": "Select application appearance theme mode",
  "light_mode": "Light Mode",
  "dark_mode": "Dark Mode",
  "start_your_journey": "Start Your Journey",
  "register_desc":
      "Create your professional healthcare workspace in minutes. Join thousands of clinics scaling with CareDesk.",
  // "create_account": "Create Account",
  "register_sub_desc": "Join our community and manage your clinic better.",
  "already_have_account": "Already have an account?",
  "sign_in": "Sign In",
  "display_name": "Display Name",
  "login_to_dashboard": "Login to Dashboard",
  "login_sub_desc": "Welcome back! Please enter your details.",
  "forgot_password": "Forgot Password?",
  "new_to_caredesk": "New to CareDesk?",
  "caredesk_pro": "CareDesk Pro",
  "the_complete_ecosystem_for_modern_healthcare_management_experience_the_future_of_clinic_operations":
      "The complete ecosystem for modern healthcare management. Experience the future of clinic operations.",
  "activity_new_appointment_detail": "Dr. Sarah with Patient Ahmed Ali",
  "todays_appointments": "Today's Appointments",
  "view_all": "View All",
  "confirmed": "Confirmed",
  // "pending": "Pending",
  "waiting": "Waiting",
  "recent_patients": "Recent Patients",
  "see_all": "See All",
  "last_visit": "Last Visit",
  "doctors_availability": "Doctors Availability",
  "online_count": "12 Online",
  "cardiologist": "Cardiologist",
  "neurologist": "Neurologist",
  "pediatrician": "Pediatrician",
  "general_surgeon": "General Surgeon",
  "available": "Available",
  "busy": "Busy",
  "on_break": "On Break",
  "system_alerts": "System Alerts",
  "missed_appointments": "Missed Appointments",
  "missed_appointments_desc": "3 patients missed their scheduled time today.",
  "pending_invoices_temp": "Pending Invoices",
  "pending_invoices_desc": "There are 5 overdue payments requiring attention.",
  "inventory_low": "Inventory Low",
  "inventory_low_desc": "Medical supplies for Room 4 are running low.",
  "pdf_document": "PDF Document (.pdf)",
  "excel_spreadsheet": "Excel Spreadsheet (.xlsx)",
  "csv_file": "CSV File (.csv)",
  "feature_coming_soon": "This feature is coming soon!",
  "patients_directory": "Patients Directory",
  "new_patient": "New Patient",
  "total_patients": "Total Patients",
  "all_registered": "All Registered",
  "active_patients": "Active Patients",
  "currently_active": "Currently Active",
  "inactive": "Inactive",
  "deactivated": "Deactivated",
  "new_this_month": "New This Month",
  "vs_last_month_up": "vs last month ↑",
  "search_by_name_or_phone": "Search by name or phone...",
  "all": "All",
  "active": "Active",
  "show_label": "Show:",
  "patient": "Patient",
  "medical_info": "Medical Info",
  "contact": "Contact",
  "status": "Status",
  "actions": "Actions",
  "view_record": "View Record",
  "edit_patient": "Edit Patient",
  "more_options": "More options",
  "deactivate_patient": "Deactivate Patient",
  "already_inactive": "Already Inactive",
  "loading_patients": "Loading patients...",
  "no_patients_found": "No Patients Found",
  "try_adjusting_search_or_filters": "Try adjusting your search or filters",
  "add_first_patient": "Add First Patient",
  "never_visited": "Never Visited",
  "recent_visit": "Recent visit",
  "no_phone": "No Phone",
  "no_email": "No Email",
  "yrs": "yrs",
  "female": "Female",
  "male": "Male",
  "unknown": "Unknown",
  "showing": "Showing",
  "of": "of",
  "results": "results",
  "edit_patient_profile": "Edit Patient Profile",
  "register_new_patient": "Register New Patient",
  "edit_profile": "Edit Profile",
  "registration": "Registration",
  "personal_information": "Personal Information",
  "full_name_required": "Full Name *",
  "name_required_error": "Name is required",
  "phone_number_required": "Phone Number *",
  "phone_required_error": "Phone is required",
  "enter_valid_phone": "Enter a valid phone",
  "email_address": "Email Address",
  "invalid_email": "Invalid email",
  "date_of_birth": "Date of Birth",
  "medical_background": "Medical Background",
  "general_medical_history_notes": "General Medical History & Notes",
  "chronic_diseases_and_medications": "Chronic Diseases & Medications",
  "medical_files_and_attachments": "Medical Files & Attachments",
  "address_and_emergency_contact": "Address & Emergency Contact",
  "home_address": "Home Address",
  "emergency_contact_name": "Emergency Contact Name",
  "emergency_contact_phone": "Emergency Contact Phone",
  "update_patient_records": "Update Patient Records",
  "register_new_clinic_patient": "Register New Clinic Patient",
  "fill_required_fields_desc":
      "Fill all required fields (*). Adding chronic diseases, medications, and file scans guarantees complete logs.",
  "complete": "Complete",
  "gender_not_set": "Gender not set",
  "auto_assigned": "Auto-assigned",
  "today": "Today",
  "blood_type": "Blood Type",
  "chronic_conditions": "Chronic Conditions",
  "medications": "Medications",
  "medical_scans_docs": "Medical Scans & Docs",
  "patient_form_tip":
      "Tip: Complete all sections for the best patient care experience.",
  "gender": "Gender",
  "chronic_diseases_support": "Chronic Diseases Support",
  "chronic_diseases_desc":
      "Indicate if this patient suffers from any long-term chronic conditions to help tailor their medical chart.",
  "has_chronic_disease": "Has Chronic Disease?",
  "select_matching_diseases": "Select all matching diseases:",
  "add_custom_disease_hint": "Add Custom Disease (e.g. Celiac disease)",
  "current_medications_support": "Current Medications Support",
  "current_medications_desc":
      "Document drugs and dosage schedules the patient is currently administering.",
  "currently_taking_medication": "Currently taking medication?",
  "no_medications_added_desc":
      "No medications added yet. Click \"+ Add Medication Entry\" below to register one.",
  "add_medication_entry": "Add Medication Entry",
  "medication_name": "Medication Name",
  "dosage_hint": "Dosage (e.g. 500mg)",
  "medication_notes_hint": "Notes (e.g. Twice daily)",
  "medical_attachments_upload_system": "Medical Attachments Upload System",
  "medical_attachments_desc":
      "Upload medical reports, MRI scans, laboratory blood tests, invoices, and physical records (Images, PDF, Excel sheets supported).",
  "uploading_files_wait": "Uploading files, please wait...",
  "click_to_browse_files": "Click here to browse files",
  "supports_file_types": "Supports: JPEG, PNG, PDF document, Excel (XLSX)",
  "selected_files": "Selected Files",
  "yes": "Yes",
  // "no": "No",
  "discard": "Discard",
  "saving": "Saving...",
  "failed_to_pick_files": "Failed to pick files",
  "diabetes": "Diabetes",
  "hypertension": "Hypertension",
  "asthma": "Asthma",
  "heart_disease": "Heart Disease",
  "thyroid_disorder": "Thyroid Disorder",
  "arthritis": "Arthritis",
  "other": "Other",
  "id": "ID",
  "registered": "Registered",
  "image": "Image",
  "excel": "Excel",
  "pdf": "PDF",
  "patient_medical_record": "Patient Medical Record",
  "back_to_list": "Back to List",
  "active_chart": "Active Chart",
  "relationship": "Relationship",
  "family_representative": "Family Representative",
  "medical_summary": "Medical Summary",
  "no_chronic_recorded": "No chronic diseases recorded on this chart.",
  "current_active_medications": "Current Active Medications",
  "no_active_medications": "No active medications registered.",
  "general_medical_logs": "General Medical Logs",
  "no_attachments_recorded":
      "No laboratory test scans, PDFs, or invoices attached.",
  "files_grid": "Files Grid:",
  "download_completed": "Download Completed",
  "saved_locally": "saved locally.",
  "visual_scan_simulation": "Visual scan simulation active.",
  "click_download_simulation":
      "Clicking \"Download\" simulates files fetching.",
  "document_name": "Document Name:",
  "saas_simulation_desc":
      "SaaS Simulation: Document opening, editing, and downloading is enabled.",
  "close": "Close",
  "open_download": "Open/Download",
  "file_downloaded": "File Downloaded",
  "retrieved_successfully": "Successfully retrieved",
  "visits_history_timeline": "Visits History Timeline",
  "latest_visit": "Latest Visit",
  "not_specified": "Not specified",
  "no_notes": "No notes",
  "reason": "Reason",
  "viewer": "Viewer",
  "users_management": "Users Management",
  "add_new_user": "Add New User",
  "no_users_found": "No users found",
  "user": "User",
  // "email": "Email",
  "role": "Role",
  "user_details": "User Details",
  "role_level_id": "Role Level ID",
  "view_details": "View Details",
  "edit_user": "Edit User",
  "delete_user": "Delete User",
  "delete_user_confirm":
      "Are you sure you want to permanently delete @name from staff list?",
  "user_deleted_success": "User deleted successfully from system registries.",
  "create_new_user": "Create New User",
  "create": "Create",
  "basic_information": "Basic Information",
  "personal_details_subtitle": "Personal details and contact information",
  // "account_settings": "Account Settings",
  "assign_roles_subtitle": "Assign roles and management permissions",
  "discard_changes": "Discard Changes",
  // "save_changes": "Save Changes",
  // "create_account": "Create Account",
  "appointments_schedule": "Appointments Schedule",
  "view_calendar": "View Calendar",
  "new_appointment": "New Appointment",
  "no_appointments_slotted": "No Appointments Slotted",
  "no_appointments_desc":
      "Keep track of patient consultations. Book a new time slot to get started.",
  "book_appointment": "Book Appointment",
  "time": "Time",
  "doctor": "Doctor",
  "visit_type": "Visit Type",
  "cancel_appointment": "Cancel Appointment",
  "complete_appointment": "Complete Appointment",
  "reschedule_slot": "Reschedule Slot",
  "remove_log": "Remove Log",
  "scheduled": "Scheduled",
  "consultation": "Consultation",
  "followup": "Follow-up",
  "routine": "Routine",
  "reschedule_appointment": "Reschedule Appointment",
  "book_new_appointment": "Book New Appointment",
  "reschedule": "Reschedule",
  "booking": "Booking",
  "select_patient": "Select Patient",
  "attending_doctor": "Attending Doctor",
  "not_assigned": "Not assigned",
  "slotted_date": "Slotted Date",
  "slotted_time": "Slotted Time",
  "current_status": "Current Status",
  "conflict_warning":
      "Make sure there are no schedule conflicts for the chosen doctor at this time.",
  "reschedule_banner_title": "Reschedule Clinical Appointment",
  "book_banner_title": "Book a New Clinical Consultation",
  "banner_subtitle":
      "Set visit type, assign specialist doctors, and reserve slots instantly in real-time.",
  "choose_patient": "Choose Patient *",
  "patient_required": "Patient selection is required",
  "assign_doctor": "Assign Specialist Doctor *",
  "doctor_required": "Doctor selection is required",
  "appointment_date": "Appointment Date *",
  "choose_date": "Choose Date",
  "time_slot": "Time Slot *",
  "select_time_slot": "Select Time Slot",
  "visit_type_label": "Visit Type *",
  "appointment_status_label": "Appointment Status *",
  "admin_notes": "Administrative Notes / Consultation Reasons",
  "notes_hint": "Describe the main cause, specific allergies or details...",
  // "discard": "Discard",
  // "saving": "Saving...",
  "input_error": "Input Error",
  "fields_required": "Please complete all required fields (*)",
  "emergency": "Emergency",
  "checkup": "Check-up",
  "appointments_calendar": "Appointments Calendar",
  "calendar_view": "Calendar View",
  "table_list_view": "Table List View",
  "book_slot": "Book Slot",
  "month_label": "Month",
  "week_label": "Week",
  "day_label": "Day",
  "agenda_slots_booked": "Agenda for selected date (@count slots booked)",
  "no_consultations_booked": "No consultations booked. Click to reserve.",
  "with_doctor_at_time": "With @doctor at @time",
  "mark_as_completed": "Mark as Completed",
  "cancel_slot": "Cancel Slot",
  "remove_permanently": "Remove Permanently",
  "specialist_insights": "Specialist Insights",
  "total_scheduled": "Total Scheduled",
  "confirmed_slots": "Confirmed Slots",
  "completed_vis": "Completed Vis.",
  "physician_availability": "Physician Availability Today",
  // "active": "Active",
  "on_call": "On Call",
  "january": "January",
  "february": "February",
  "march": "March",
  "april": "April",
  "may": "May",
  "june": "June",
  "july": "July",
  "august": "August",
  "september": "September",
  "october": "October",
  "november": "November",
  "december": "December",
  "sun": "Sun",
  "mon": "Mon",
  "tue": "Tue",
  "wed": "Wed",
  "thu": "Thu",
  "fri": "Fri",
  "sat": "Sat",
  "edit_role": "Edit Role",
  "define_role": "Define Role",
  "role_identity": "Role Identity",
  "role_identity_subtitle": "Give this role a name and description",
  "role_name": "Role Name",
  "role_name_hint": "e.g. Senior Doctor",
  "permissions_matrix": "Permissions Matrix",
  "permissions_matrix_subtitle": "Select which actions this role can perform",
  "save_role": "Save Role",
  "create_role": "Create Role",
  "billing": "Billing",
  "view_patients": "View Patients",
  "create_patient": "Create Patient",
  // "edit_patient": "Edit Patient",
  "delete_patient": "Delete Patient",
  "view_appointments": "View Appointments",
  "create_appointment": "Create Appointment",
  "view_invoices": "View Invoices",
  "edit_invoices": "Edit Invoices",
  "roles_permissions": "Roles & Permissions",
  "define_new_role": "Define New Role",
  "permissions_count": "Permissions Count",
  "delete_role": "Delete Role",
  "delete_role_confirmation":
      "Are you sure you want to permanently delete role \"@role\"?",
  "success": "Success",
  "role_removed_success": "Role removed successfully.",
  "system_settings": "System Settings",
  "settings": "Settings",
  "profile_settings": "Profile Settings",
  "profile_settings_sub": "Manage your personal info & bio",
  // "account_settings": "Account Settings",
  "account_settings_sub": "Update password & active sessions",
  // "general_settings": "General Settings",
  "general_settings_sub": "Clinic details & localizations",
  // "notifications": "Notifications",
  "notifications_sub": "Configure system notification alerts",
  "security": "Security",
  "security_sub": "Two-factor auth & credential safety",
  "theme_settings": "Theme Settings",
  "theme_settings_sub": "Light, dark & color themes",
  "language": "Language",
  "language_sub": "Choose interface language & region",
  "system_settings_sub": "Advanced debug & platform config",
  "personal_profile": "Personal Profile",
  "personal_profile_sub":
      "Manage how your public profile details appear in the CareDesk system.",

  "professional_title": "Professional Title",
  "account_security": "Account Security",
  "account_security_sub":
      "Change password or manage current authenticated sessions.",
  "current_password": "Current Password",

  "active_sessions": "Active Sessions",
  "clinic_name": "Clinic Name",
  "contact_phone": "Contact Phone",
  "address": "Address",
  "default_timezone": "Default Timezone",
  "currency_symbol": "Currency Symbol",
  "notification_controls": "Notification Controls",
  "notification_controls_sub":
      "Toggle specific notification channels on or off according to preference.",
  "push_notifications": "Push Notifications",
  "push_notifications_sub": "Show desktop and mobile real-time push alerts",
  "email_alerts": "Email Alerts",
  "email_alerts_sub": "Receive medical logs and daily shift digests via email",
  "appointment_reminders": "Appointment Reminders",
  "appointment_reminders_sub":
      "Send automated reminders to patients 24 hours prior",
  "maintenance_updates": "Maintenance Updates",
  "maintenance_updates_sub":
      "Get notifications on upcoming scheduled system updates",
  "security_safeguards": "Security Safeguards",
  "security_safeguards_sub":
      "Activate strict compliance controls to protect critical healthcare data.",
  "two_factor_auth": "Two-Factor Authentication (2FA)",
  "two_factor_auth_sub": "Requires OTP verification code during login sessions",
  "biometric_credentials": "Biometric Credentials",
  "biometric_credentials_sub":
      "Allows fingerprint or face unlock on compatible mobile platforms",
  "auto_lock_session": "Auto-Lock Inactive Session",
  "auto_lock_session_sub":
      "Automatically locks active session after 15 minutes of inactivity",
  "theme_customization": "Theme Customization",
  "theme_customization_sub":
      "Change the visual look of CareDesk by switching styles or accent colors.",
  "display_mode": "Display Mode",
  "primary_accent_color": "Primary Accent Color",
  // "light_mode": "Light",
  // "dark_mode": "Dark",
  "system_default": "System Default",
  "blue": "Blue",
  "green": "Green",
  "purple": "Purple",
  "teal": "Teal",
  "orange": "Orange",
  "system_language": "System Language",
  "system_language_sub":
      "Switch localized text displays across all navigation modules.",
  "primary_language": "Primary Language",
  // "english": "English",
  // "arabic": "Arabic (العربية)",
  "french": "French (Français)",
  "advanced_developer_settings": "Advanced Developer Settings",
  "advanced_developer_settings_sub":
      "Fine-tune system variables, configure server APIs or toggle maintenance states.",
  "debug_log_mode": "Debug Log Mode",
  "debug_log_mode_sub":
      "Output verbose warnings and execution logs to inspector consoles",
  "platform_maintenance_mode": "Platform Maintenance Mode",
  "platform_maintenance_mode_sub":
      "locks system for standard receptionists, allows only administrators",
  "save_settings": "Save Settings",
  "settings_saved_success": "Settings saved successfully!",
  "active_now": "Active now",
  "two_hours_ago": "2 hours ago",
  "revoke": "Revoke",
  "login_security": "Login & Security",
  "sign_out": "Sign Out",
  "sign_out_confirm":
      "Are you sure you want to sign out of your CareDesk account?",
  "personal_information_sub": "Update your profile details and public identity",
  "your_name": "Your name",
  "phone_hint": "e.g. +1 234 567 890",
  "professional_bio": "Professional Bio",
  "professional_bio_hint": "A short description of your role and experience",
  "update_profile": "Update Profile",
  "security_settings": "Security Settings",
  "security_settings_sub": "Manage your password and account security",
};
