import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:getx_base_code/src/Core/Constants/Strings/Assets/app_basic_icons.dart';
import 'package:getx_base_code/src/Core/Constants/Strings/Assets/app_images.dart';
import 'package:getx_base_code/src/Core/Services/lang_service/translate_extension.dart';
import 'package:getx_base_code/src/Core/Utils/Extensions/screen_spaces_extension.dart';
import 'package:getx_base_code/src/Features/LocalAuth/presentation/manager/login_user_local_controller.dart';
import 'package:getx_base_code/src/Features/LocalAuth/presentation/manager/register_user_local_controller.dart';
import 'package:getx_base_code/src/Features/LocalAuth/presentation/pages/add_role_page.dart';
import 'package:getx_base_code/src/Features/LocalAuth/presentation/widgets/select_roles_sheet.dart';
import 'package:getx_base_code/src/Shared/Presentation/Widgets/Animation/animated_wrapper.dart';

import '../../../../Core/Constants/Decorations/app_Insets.dart';
import '../../../../Core/Constants/Decorations/app_physics.dart';
import '../../../../Core/Constants/Strings/Assets/app_icons.dart';
import '../../../../Core/Services/pin_code.dart';
import '../../../../Core/Styles/Colors/app_colors.dart';
import '../../../../Core/Utils/Validation/Implementation/PasswordValidator/confirm_password_validator.dart';
import '../../../../Core/Utils/Validation/app_validator.dart';
import '../../../../Shared/Presentation/Widgets/AppBars/app_bars.dart';
import '../../../../Shared/Presentation/Widgets/GeneralWidgets/Buttons/Basic/custom_rounded_button.dart';
import '../../../../Shared/Presentation/Widgets/GeneralWidgets/Text/custom_text_lib.dart';
import '../../../../Shared/Presentation/Widgets/GeneralWidgets/TextFields/Default/app_password_field.dart';
import '../../../../Shared/Presentation/Widgets/GeneralWidgets/TextFields/Default/src/phone_form_field.dart';
import '../../../../Shared/Presentation/Widgets/GeneralWidgets/TextFields/app_text_field.dart';
import '../manger/change_password_controller.dart';
import '../manger/check_verification_code_controller.dart';
import '../manger/reset_password_controller.dart';
import '../widgets/auth_header.dart';
import '../widgets/footer_login.dart';

part 'change_password_page.dart';
// part 'enter_password_page.dart';
// part 'enter_phone_page.dart';
part 'login_page.dart';
part 'register_page.dart';
part 'reset_password_page.dart';
part 'verification_page.dart';
